import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Icon } from '../components/Icon';
import { useOrganization } from '../contexts/OrganizationContext';
import { formatCleaningDateTime, formatCleaningMoney, type CleaningInterventionRecord } from '../features/cleaning/types';
import { supabase } from '../lib/supabase';

export function CleaningInterventionsPage() {
  const { organization } = useOrganization(); const [rows, setRows] = useState<CleaningInterventionRecord[]>([]); const [status, setStatus] = useState('all'); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { if (!organization || !supabase) { setLoading(false); return; } const client = supabase; const organizationId = organization.id; let active = true; async function load() { setLoading(true); const from = new Date(); from.setDate(from.getDate() - 30); const to = new Date(); to.setDate(to.getDate() + 45); const { data, error: loadError } = await client.from('cleaning_interventions').select('*,cleaning_sites(name,address,city,instructions,cleaning_clients(company_name)),cleaning_agents(first_name,last_name)').eq('organization_id', organizationId).gte('starts_at', from.toISOString()).lte('starts_at', to.toISOString()).order('starts_at', { ascending: false }); if (!active) return; if (loadError) setError(loadError.message); else setRows((data ?? []) as CleaningInterventionRecord[]); setLoading(false); } void load(); return () => { active = false; }; }, [organization?.id]);
  const filtered = useMemo(() => { const needle = query.toLocaleLowerCase('fr').trim(); return rows.filter((row) => (status === 'all' || row.status === status) && (!needle || [row.title, row.cleaning_sites?.name, row.cleaning_sites?.cleaning_clients?.company_name, row.cleaning_agents?.first_name, row.cleaning_agents?.last_name].filter(Boolean).join(' ').toLocaleLowerCase('fr').includes(needle))); }, [rows, status, query]);
  if (!organization) return null;
  return <div className="page cleaning-page"><header className="page-header"><div><p className="eyebrow">NETTOYAGE</p><h1>Interventions</h1><p>Suivi centralisé des passages planifiés, en cours et terminés.</p></div><Link className="primary-button" to="/planning"><Icon name="plus" size={18}/>Planifier</Link></header>{error && <div className="error-message page-message">{error}</div>}<section className="panel cleaning-list-panel"><div className="cleaning-toolbar"><div className="cleaning-filter-group"><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">Tous les statuts</option><option value="planned">Planifiées</option><option value="in_progress">En cours</option><option value="completed">Terminées</option><option value="canceled">Annulées</option></select><input type="search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Site, client, agent…"/></div><strong>{filtered.length} résultat{filtered.length > 1 ? 's' : ''}</strong></div>{loading ? <div className="cleaning-empty">Chargement…</div> : filtered.length === 0 ? <div className="cleaning-empty"><Icon name="clipboard" size={30}/><strong>Aucune intervention</strong></div> : <div className="cleaning-card-list">{filtered.map((row) => <article className="cleaning-record-card" key={row.id}><span className="cleaning-record-icon"><Icon name="clipboard" size={20}/></span><div className="cleaning-record-main"><strong>{row.cleaning_sites?.name} · {row.title}</strong><span>{row.cleaning_sites?.cleaning_clients?.company_name} · {row.cleaning_agents?.first_name} {row.cleaning_agents?.last_name}</span><small>{formatCleaningDateTime(row.starts_at)} · {formatCleaningMoney(row.planned_price_cents)}</small>{row.report_text && <p className="cleaning-inline-note">{row.report_text}</p>}</div><span className={`cleaning-status-pill ${row.status}`}>{row.status === 'planned' ? 'Planifiée' : row.status === 'in_progress' ? 'En cours' : row.status === 'completed' ? 'Terminée' : 'Annulée'}</span></article>)}</div>}</section></div>;
}
