import { useEffect, useState } from 'react';
import { Icon } from '../components/Icon';
import { useOrganization } from '../contexts/OrganizationContext';
import { downloadCleaningReportPdf } from '../features/cleaning/visitReportPdf';
import { formatCleaningDateTime, type CleaningInterventionRecord } from '../features/cleaning/types';
import { supabase } from '../lib/supabase';

export function CleaningReportsPage() {
  const { organization } = useOrganization(); const [rows, setRows] = useState<CleaningInterventionRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { if (!organization || !supabase) { setLoading(false); return; } const client = supabase; const organizationId = organization.id; let active = true; async function load() { const { data, error: loadError } = await client.from('cleaning_interventions').select('*,cleaning_sites(name,address,city,instructions,cleaning_clients(company_name)),cleaning_agents(first_name,last_name)').eq('organization_id', organizationId).eq('status', 'completed').order('actual_ended_at', { ascending: false }).limit(100); if (!active) return; if (loadError) setError(loadError.message); else setRows((data ?? []) as CleaningInterventionRecord[]); setLoading(false); } void load(); return () => { active = false; }; }, [organization?.id]);
  if (!organization) return null;
  return <div className="page cleaning-page"><header className="page-header"><div><p className="eyebrow">NETTOYAGE</p><h1>Rapports de passage</h1><p>Preuves d’intervention, observations et export PDF pour le client.</p></div></header>{error && <div className="error-message page-message">{error}</div>}<section className="panel cleaning-list-panel">{loading ? <div className="cleaning-empty">Chargement…</div> : rows.length === 0 ? <div className="cleaning-empty"><Icon name="file" size={30}/><strong>Aucun rapport disponible</strong><span>Les interventions terminées apparaîtront ici.</span></div> : <div className="cleaning-card-list">{rows.map((row) => <article className="cleaning-record-card cleaning-report-card" key={row.id}><span className="cleaning-record-icon"><Icon name="file" size={20}/></span><div className="cleaning-record-main"><strong>{row.cleaning_sites?.name}</strong><span>{row.cleaning_sites?.cleaning_clients?.company_name} · {row.cleaning_agents?.first_name} {row.cleaning_agents?.last_name}</span><small>Terminé {row.actual_ended_at ? formatCleaningDateTime(row.actual_ended_at) : formatCleaningDateTime(row.ends_at)}</small><p className="cleaning-inline-note">{row.report_text || 'Passage terminé sans commentaire.'}</p>{(row.before_photo_url || row.after_photo_url) && <div className="cleaning-report-thumbnails">{row.before_photo_url && <img src={row.before_photo_url} alt="Avant"/>}{row.after_photo_url && <img src={row.after_photo_url} alt="Après"/>}</div>}</div><button className="secondary-button compact-button" onClick={() => void downloadCleaningReportPdf(organization, row)}><Icon name="file" size={16}/>PDF</button></article>)}</div>}</section></div>;
}
