import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Icon } from '../components/Icon';
import { organizationHasFeature } from '../config/planEntitlements';
import { useAuth } from '../contexts/AuthContext';
import { useOrganization } from '../contexts/OrganizationContext';
import { restaurantErrorMessage, safeRestaurantStorageArray } from '../features/restaurant/runtime';
import { formatRestaurantMoney, nullableRestaurantText, type RestaurantStockItemRecord, type RestaurantSupplierRecord, type RestaurantWasteRecord } from '../features/restaurant/types';
import { supabase } from '../lib/supabase';

const supplierInitial = { name: '', contactName: '', email: '', phone: '', notes: '' };
const stockInitial = { supplierId: '', name: '', category: '', unit: 'kg', quantity: '0', minimumQuantity: '0', unitCost: '0' };
const wasteInitial = { stockItemId: '', itemName: '', quantity: '1', unit: 'kg', reason: 'Périmé', estimatedCost: '0' };

export function RestaurantStockPage() {
  const { organization } = useOrganization(); const { user, demoMode } = useAuth();
  const [suppliers, setSuppliers] = useState<RestaurantSupplierRecord[]>([]); const [items, setItems] = useState<RestaurantStockItemRecord[]>([]); const [waste, setWaste] = useState<RestaurantWasteRecord[]>([]);
  const [supplierForm, setSupplierForm] = useState(supplierInitial); const [stockForm, setStockForm] = useState(stockInitial); const [wasteForm, setWasteForm] = useState(wasteInitial);
  const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [saving, setSaving] = useState(false);
  const advanced = Boolean(organization && organizationHasFeature(organization, 'restaurant_advanced_stock')); const wasteEnabled = Boolean(organization && organizationHasFeature(organization, 'restaurant_waste'));

  async function load() { if (!organization) return; setError(''); if (demoMode || !supabase) { setSuppliers(safeRestaurantStorageArray<RestaurantSupplierRecord>(`ncr-restaurant-suppliers-${organization.id}`)); setItems(safeRestaurantStorageArray<RestaurantStockItemRecord>(`ncr-restaurant-stock-${organization.id}`)); setWaste(safeRestaurantStorageArray<RestaurantWasteRecord>(`ncr-restaurant-waste-${organization.id}`)); return; } const requests = [supabase.from('restaurant_suppliers').select('*').eq('organization_id', organization.id).eq('status', 'active').order('name'), supabase.from('restaurant_stock_items').select('*,restaurant_suppliers(name)').eq('organization_id', organization.id).eq('status', 'active').order('name')]; const [supplierResult, stockResult] = await Promise.all(requests); const firstError = supplierResult.error || stockResult.error; if (firstError) setError(firstError.message); setSuppliers((supplierResult.data ?? []) as RestaurantSupplierRecord[]); setItems((stockResult.data ?? []) as RestaurantStockItemRecord[]); if (wasteEnabled) { const { data, error: wasteError } = await supabase.from('restaurant_waste_records').select('*').eq('organization_id', organization.id).order('recorded_at', { ascending: false }).limit(30); if (wasteError) setError(wasteError.message); setWaste((data ?? []) as RestaurantWasteRecord[]); } else setWaste([]); }
  useEffect(() => { void load(); }, [organization?.id, organization?.plan, demoMode]);

  async function addSupplier(event: FormEvent) { event.preventDefault(); if (!organization || !user) return; setSaving(true); try { let created: RestaurantSupplierRecord; const payload = { organization_id: organization.id, name: supplierForm.name.trim(), contact_name: nullableRestaurantText(supplierForm.contactName), email: nullableRestaurantText(supplierForm.email)?.toLowerCase() ?? null, phone: nullableRestaurantText(supplierForm.phone), notes: nullableRestaurantText(supplierForm.notes), created_by: user.id }; if (demoMode || !supabase) { created = { id: crypto.randomUUID(), ...payload, status: 'active' }; localStorage.setItem(`ncr-restaurant-suppliers-${organization.id}`, JSON.stringify([...suppliers, created])); } else { const { data, error: insertError } = await supabase.from('restaurant_suppliers').insert(payload).select('*').single(); if (insertError) throw insertError; created = data as RestaurantSupplierRecord; } setSuppliers((current) => [...current, created]); setSupplierForm(supplierInitial); setSuccess('Le fournisseur a été ajouté.'); } catch (caught) { setError(restaurantErrorMessage(caught, 'Création impossible.')); } finally { setSaving(false); } }

  async function addStock(event: FormEvent) { event.preventDefault(); if (!organization || !user) return; setSaving(true); const supplier = suppliers.find((row) => row.id === stockForm.supplierId); const payload = { organization_id: organization.id, supplier_id: stockForm.supplierId || null, name: stockForm.name.trim(), category: nullableRestaurantText(stockForm.category), unit: stockForm.unit.trim() || 'unité', quantity: Math.max(0, Number(stockForm.quantity.replace(',', '.')) || 0), minimum_quantity: Math.max(0, Number(stockForm.minimumQuantity.replace(',', '.')) || 0), unit_cost_cents: Math.max(0, Math.round((Number(stockForm.unitCost.replace(',', '.')) || 0) * 100)), created_by: user.id }; try { let created: RestaurantStockItemRecord; if (demoMode || !supabase) { created = { id: crypto.randomUUID(), ...payload, status: 'active', restaurant_suppliers: supplier ? { name: supplier.name } : null }; localStorage.setItem(`ncr-restaurant-stock-${organization.id}`, JSON.stringify([...items, created])); } else { const { data, error: insertError } = await supabase.from('restaurant_stock_items').insert(payload).select('*,restaurant_suppliers(name)').single(); if (insertError) throw insertError; created = data as RestaurantStockItemRecord; } setItems((current) => [...current, created]); setStockForm(stockInitial); setSuccess('Le produit a été ajouté au stock.'); } catch (caught) { setError(restaurantErrorMessage(caught, 'Création impossible.')); } finally { setSaving(false); } }

  async function adjust(row: RestaurantStockItemRecord, delta: number) { if (!organization) return; const quantity = Math.max(0, Number(row.quantity) + delta); try { if (demoMode || !supabase) { const next = items.map((item) => item.id === row.id ? { ...item, quantity } : item); localStorage.setItem(`ncr-restaurant-stock-${organization.id}`, JSON.stringify(next)); setItems(next); } else { const { error: updateError } = await supabase.from('restaurant_stock_items').update({ quantity }).eq('organization_id', organization.id).eq('id', row.id); if (updateError) throw updateError; setItems((current) => current.map((item) => item.id === row.id ? { ...item, quantity } : item)); } } catch (caught) { setError(caught instanceof Error ? caught.message : 'Mise à jour impossible.'); } }

  async function addWaste(event: FormEvent) { event.preventDefault(); if (!organization || !user || !wasteEnabled) return; setSaving(true); const item = items.find((row) => row.id === wasteForm.stockItemId); const payload = { organization_id: organization.id, stock_item_id: wasteForm.stockItemId || null, item_name: wasteForm.itemName.trim() || item?.name || 'Produit', quantity: Math.max(0.01, Number(wasteForm.quantity.replace(',', '.')) || 1), unit: wasteForm.unit.trim() || item?.unit || 'unité', reason: wasteForm.reason.trim(), estimated_cost_cents: Math.max(0, Math.round((Number(wasteForm.estimatedCost.replace(',', '.')) || 0) * 100)), recorded_by: user.id }; try { let created: RestaurantWasteRecord; if (demoMode || !supabase) { created = { id: crypto.randomUUID(), ...payload, recorded_at: new Date().toISOString() }; const next = [created, ...waste]; localStorage.setItem(`ncr-restaurant-waste-${organization.id}`, JSON.stringify(next)); } else { const { data, error: insertError } = await supabase.from('restaurant_waste_records').insert(payload).select('*').single(); if (insertError) throw insertError; created = data as RestaurantWasteRecord; } setWaste((current) => [created, ...current]); setWasteForm(wasteInitial); setSuccess('La perte a été enregistrée.'); } catch (caught) { setError(restaurantErrorMessage(caught, 'Enregistrement impossible.')); } finally { setSaving(false); } }

  const lowStock = useMemo(() => items.filter((row) => Number(row.quantity) <= Number(row.minimum_quantity)), [items]); const stockValue = items.reduce((total, row) => total + Number(row.quantity) * row.unit_cost_cents, 0); const wasteValue = waste.reduce((total, row) => total + row.estimated_cost_cents, 0);
  if (!organization) return null;
  return <div className="page restaurant-page"><header className="page-header"><div><p className="eyebrow">RESTAURATION</p><h1>Stocks & fournisseurs</h1><p>Suis les quantités, seuils, coûts et pertes alimentaires.</p></div></header>{error && <div className="error-message page-message">{error}</div>}{success && <div className="success-message page-message">{success}</div>}
    <section className="stats-grid"><article className="stat-card"><span className="stat-icon"><Icon name="briefcase" size={22}/></span><span>Références actives</span><strong>{items.length}</strong><small>{suppliers.length} fournisseur{suppliers.length > 1 ? 's' : ''}</small></article><article className="stat-card"><span className="stat-icon"><Icon name="alert" size={22}/></span><span>Sous le seuil</span><strong>{lowStock.length}</strong><small>commandes à préparer</small></article><article className="stat-card"><span className="stat-icon"><Icon name="creditCard" size={22}/></span><span>Valeur estimée</span><strong>{advanced ? formatRestaurantMoney(stockValue) : '—'}</strong><small>{advanced ? 'selon les coûts unitaires' : 'offre Professionnelle'}</small></article><article className="stat-card"><span className="stat-icon"><Icon name="chart" size={22}/></span><span>Pertes enregistrées</span><strong>{wasteEnabled ? formatRestaurantMoney(wasteValue) : '—'}</strong><small>{wasteEnabled ? `${waste.length} déclaration(s)` : 'offre Professionnelle'}</small></article></section>
    <section className="restaurant-two-column"><article className="panel restaurant-form-panel"><div className="panel-header"><div><p className="eyebrow">FOURNISSEUR</p><h2>Ajouter un partenaire</h2></div></div><form className="restaurant-form-grid" onSubmit={addSupplier}><label className="full-field">Nom *<input required value={supplierForm.name} onChange={(e) => setSupplierForm({ ...supplierForm, name: e.target.value })}/></label><label>Contact<input value={supplierForm.contactName} onChange={(e) => setSupplierForm({ ...supplierForm, contactName: e.target.value })}/></label><label>Téléphone<input value={supplierForm.phone} onChange={(e) => setSupplierForm({ ...supplierForm, phone: e.target.value })}/></label><label className="full-field">E-mail<input type="email" value={supplierForm.email} onChange={(e) => setSupplierForm({ ...supplierForm, email: e.target.value })}/></label><button className="secondary-button full-field" disabled={saving}>Ajouter le fournisseur</button></form></article>
      <article className="panel restaurant-form-panel"><div className="panel-header"><div><p className="eyebrow">PRODUIT</p><h2>Ajouter au stock</h2></div></div><form className="restaurant-form-grid" onSubmit={addStock}><label className="full-field">Produit *<input required value={stockForm.name} onChange={(e) => setStockForm({ ...stockForm, name: e.target.value })}/></label><label>Catégorie<input value={stockForm.category} onChange={(e) => setStockForm({ ...stockForm, category: e.target.value })} placeholder="Épicerie, frais, boissons…"/></label><label>Fournisseur<select value={stockForm.supplierId} onChange={(e) => setStockForm({ ...stockForm, supplierId: e.target.value })}><option value="">Aucun</option>{suppliers.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Quantité<input inputMode="decimal" value={stockForm.quantity} onChange={(e) => setStockForm({ ...stockForm, quantity: e.target.value })}/></label><label>Seuil minimum<input inputMode="decimal" value={stockForm.minimumQuantity} onChange={(e) => setStockForm({ ...stockForm, minimumQuantity: e.target.value })}/></label><label>Unité<input value={stockForm.unit} onChange={(e) => setStockForm({ ...stockForm, unit: e.target.value })}/></label><label>{advanced ? 'Coût unitaire (€)' : 'Coût unitaire — Professionnelle'}<input disabled={!advanced} inputMode="decimal" value={stockForm.unitCost} onChange={(e) => setStockForm({ ...stockForm, unitCost: e.target.value })}/></label><button className="primary-button full-field" disabled={saving}>Ajouter le produit</button></form></article></section>
    <section className="panel restaurant-list-panel"><div className="panel-header"><div><p className="eyebrow">INVENTAIRE</p><h2>État des stocks</h2></div></div>{items.length === 0 ? <div className="restaurant-empty"><Icon name="briefcase" size={30}/><strong>Aucun produit</strong></div> : <div className="restaurant-stock-table"><div className="restaurant-stock-head"><span>Produit</span><span>Fournisseur</span><span>Quantité</span><span>Seuil</span><span>Actions</span></div>{items.map((row) => <div className={Number(row.quantity) <= Number(row.minimum_quantity) ? 'low' : ''} key={row.id}><span><strong>{row.name}</strong><small>{row.category || 'Sans catégorie'}</small></span><span>{row.restaurant_suppliers?.name || '—'}</span><span>{row.quantity} {row.unit}</span><span>{row.minimum_quantity} {row.unit}</span><span><button onClick={() => void adjust(row, -1)}>−</button><button onClick={() => void adjust(row, 1)}>+</button></span></div>)}</div>}</section>
    {wasteEnabled ? <section className="restaurant-two-column"><article className="panel restaurant-form-panel"><div className="panel-header"><div><p className="eyebrow">PERTES</p><h2>Déclarer du gaspillage</h2></div></div><form className="restaurant-form-grid" onSubmit={addWaste}><label className="full-field">Produit<select value={wasteForm.stockItemId} onChange={(e) => { const selected = items.find((row) => row.id === e.target.value); setWasteForm({ ...wasteForm, stockItemId: e.target.value, itemName: selected?.name ?? '', unit: selected?.unit ?? wasteForm.unit }); }}><option value="">Autre produit</option>{items.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Quantité<input inputMode="decimal" value={wasteForm.quantity} onChange={(e) => setWasteForm({ ...wasteForm, quantity: e.target.value })}/></label><label>Unité<input value={wasteForm.unit} onChange={(e) => setWasteForm({ ...wasteForm, unit: e.target.value })}/></label><label>Motif<input value={wasteForm.reason} onChange={(e) => setWasteForm({ ...wasteForm, reason: e.target.value })}/></label><label>Coût estimé (€)<input inputMode="decimal" value={wasteForm.estimatedCost} onChange={(e) => setWasteForm({ ...wasteForm, estimatedCost: e.target.value })}/></label><button className="secondary-button full-field" disabled={saving}>Enregistrer la perte</button></form></article><article className="panel"><div className="panel-header"><div><p className="eyebrow">HISTORIQUE</p><h2>Dernières pertes</h2></div></div><div className="restaurant-card-list">{waste.slice(0, 10).map((row) => <article className="restaurant-record-card" key={row.id}><span className="restaurant-record-icon danger"><Icon name="alert" size={20}/></span><div className="restaurant-record-main"><strong>{row.item_name} · {row.quantity} {row.unit}</strong><span>{row.reason}</span><small>{formatRestaurantMoney(row.estimated_cost_cents)} · {new Intl.DateTimeFormat('fr-FR', { dateStyle: 'short' }).format(new Date(row.recorded_at))}</small></div></article>)}</div></article></section> : <section className="panel restaurant-premium-teaser"><Icon name="lock" size={24}/><div><p className="eyebrow">OFFRE PROFESSIONNELLE</p><h2>Pertes, gaspillage et commandes fournisseurs</h2><p>Quantifie les pertes, estime leur coût et prépare les commandes à partir des seuils.</p></div><a className="secondary-button" href="/abonnement">Voir l’offre</a></section>}
  </div>;
}
