import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Icon } from '../components/Icon';
import { useOrganization } from '../contexts/OrganizationContext';
import { formatRestaurantDateTime, RESTAURANT_ROLE_LABELS, type RestaurantEmployeeRecord, type RestaurantShiftRecord } from '../features/restaurant/types';
import { supabase } from '../lib/supabase';

export function RestaurantEmployeePortalPage() {
  const { organization } = useOrganization(); const [employee, setEmployee] = useState<RestaurantEmployeeRecord | null>(null); const [shifts, setShifts] = useState<RestaurantShiftRecord[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!organization || !supabase) { setLoading(false); return; } let active = true; async function load() { setLoading(true); const { data: employeeData, error: employeeError } = await supabase!.rpc('current_restaurant_employee', { p_organization_id: organization!.id }); if (!active) return; if (employeeError) { setError(employeeError.message); setLoading(false); return; } const current = Array.isArray(employeeData) ? employeeData[0] : employeeData; setEmployee((current ?? null) as RestaurantEmployeeRecord | null); if (current?.id) { const start = new Date(); start.setDate(start.getDate() - 1); const end = new Date(); end.setDate(end.getDate() + 15); const { data, error: shiftError } = await supabase!.from('restaurant_shifts').select('*,restaurant_employees(first_name,last_name,role_code)').eq('organization_id', organization!.id).eq('employee_id', current.id).gte('starts_at', start.toISOString()).lt('starts_at', end.toISOString()).neq('status', 'canceled').order('starts_at'); if (shiftError) setError(shiftError.message); else setShifts((data ?? []) as RestaurantShiftRecord[]); } setLoading(false); } void load(); return () => { active = false; }; }, [organization?.id]);
  if (!organization) return null;
  if (loading) return <div className="page restaurant-page"><div className="panel restaurant-empty">Chargement de l’espace employé…</div></div>;
  return <div className="page restaurant-page restaurant-portal-page"><header className="page-header"><div><p className="eyebrow">ESPACE EMPLOYÉ</p><h1>{employee ? `Bonjour ${employee.first_name}` : 'Espace terrain'}</h1><p>{employee ? `${RESTAURANT_ROLE_LABELS[employee.role_code]} · retrouve tes prochains services et les outils du restaurant.` : 'Aucune fiche employé n’est liée à ce compte.'}</p></div></header>{error && <div className="error-message page-message">{error}</div>}{!employee ? <section className="panel restaurant-empty"><Icon name="users" size={32}/><strong>Compte non relié</strong><span>Le responsable doit associer ce compte à une fiche Employé depuis Accès équipe.</span></section> : <><section className="restaurant-portal-actions"><Link to="/planning"><Icon name="calendar" size={22}/><strong>Mon planning</strong><span>Voir mes prochains services</span></Link><Link to="/reservations"><Icon name="utensils" size={22}/><strong>Réservations</strong><span>Consulter le service</span></Link><Link to="/hygiene"><Icon name="clipboard" size={22}/><strong>Hygiène</strong><span>Faire un relevé ou une checklist</span></Link><Link to="/carte"><Icon name="file" size={22}/><strong>Carte</strong><span>Vérifier plats et allergènes</span></Link></section><section className="panel restaurant-list-panel"><div className="panel-header"><div><p className="eyebrow">MES SERVICES</p><h2>Planning à venir</h2></div></div>{shifts.length === 0 ? <div className="restaurant-empty"><Icon name="calendar" size={30}/><strong>Aucun service planifié</strong></div> : <div className="restaurant-card-list">{shifts.map((row) => <article className="restaurant-record-card" key={row.id}><span className="restaurant-record-icon"><Icon name="clock" size={20}/></span><div className="restaurant-record-main"><strong>{row.position_label || RESTAURANT_ROLE_LABELS[employee.role_code]}</strong><span>{formatRestaurantDateTime(row.starts_at)}</span><small>Fin à {new Intl.DateTimeFormat('fr-FR', { hour: '2-digit', minute: '2-digit' }).format(new Date(row.ends_at))}{row.notes ? ` · ${row.notes}` : ''}</small></div><span className="restaurant-status-pill planned">Planifié</span></article>)}</div>}</section></>}</div>;
}
