import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Icon } from '../components/Icon';
import { useAuth } from '../contexts/AuthContext';
import { useOrganization } from '../contexts/OrganizationContext';
import { nullableRestaurantText, RESTAURANT_ROLE_LABELS, type RestaurantEmployeeRecord, type RestaurantEmployeeRole } from '../features/restaurant/types';
import { supabase } from '../lib/supabase';

const emptyForm = { firstName: '', lastName: '', roleCode: 'server' as RestaurantEmployeeRole, email: '', phone: '', weeklyHours: '35' };

export function RestaurantEmployeesPage() {
  const { organization } = useOrganization(); const { user, demoMode } = useAuth();
  const [searchParams, setSearchParams] = useSearchParams();
  const [rows, setRows] = useState<RestaurantEmployeeRecord[]>([]); const [form, setForm] = useState(emptyForm); const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const formOpen = searchParams.get('new') === '1';

  useEffect(() => { if (!organization) return; let active = true; async function load() { setLoading(true); if (demoMode || !supabase) { const stored = localStorage.getItem(`ncr-restaurant-employees-${organization!.id}`); if (active) setRows(stored ? JSON.parse(stored) : []); } else { const { data, error: loadError } = await supabase.from('restaurant_employees').select('*').eq('organization_id', organization!.id).neq('status', 'archived').order('last_name'); if (active) { if (loadError) setError(loadError.message); else setRows((data ?? []) as RestaurantEmployeeRecord[]); } } if (active) setLoading(false); } void load(); return () => { active = false; }; }, [organization?.id, demoMode]);

  const filtered = useMemo(() => { const needle = query.trim().toLowerCase(); return needle ? rows.filter((row) => `${row.first_name} ${row.last_name} ${RESTAURANT_ROLE_LABELS[row.role_code]} ${row.email ?? ''}`.toLowerCase().includes(needle)) : rows; }, [rows, query]);

  async function createEmployee(event: FormEvent) { event.preventDefault(); if (!organization || !user) return; setSaving(true); setError(''); setSuccess(''); const payload = { organization_id: organization.id, first_name: form.firstName.trim(), last_name: form.lastName.trim(), role_code: form.roleCode, email: nullableRestaurantText(form.email)?.toLowerCase() ?? null, phone: nullableRestaurantText(form.phone), weekly_hours: Math.max(0, Math.min(80, Number(form.weeklyHours) || 0)), created_by: user.id }; try { let created: RestaurantEmployeeRecord; if (demoMode || !supabase) { created = { id: crypto.randomUUID(), ...payload, linked_user_id: null, status: 'active', created_at: new Date().toISOString() }; localStorage.setItem(`ncr-restaurant-employees-${organization.id}`, JSON.stringify([...rows, created])); } else { const { data, error: insertError } = await supabase.from('restaurant_employees').insert(payload).select('*').single(); if (insertError) throw insertError; created = data as RestaurantEmployeeRecord; } setRows((current) => [...current, created].sort((a, b) => a.last_name.localeCompare(b.last_name, 'fr'))); setForm(emptyForm); setSearchParams({}); setSuccess('L’employé a bien été ajouté.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Création impossible.'); } finally { setSaving(false); } }

  async function archive(row: RestaurantEmployeeRecord) { if (!organization || !window.confirm(`Archiver ${row.first_name} ${row.last_name} ?`)) return; try { if (demoMode || !supabase) localStorage.setItem(`ncr-restaurant-employees-${organization.id}`, JSON.stringify(rows.filter((item) => item.id !== row.id))); else { const { error: updateError } = await supabase.from('restaurant_employees').update({ status: 'archived' }).eq('organization_id', organization.id).eq('id', row.id); if (updateError) throw updateError; } setRows((current) => current.filter((item) => item.id !== row.id)); setSuccess('L’employé a été archivé.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Archivage impossible.'); } }

  if (!organization) return null;
  return <div className="page restaurant-page"><header className="page-header"><div><p className="eyebrow">RESTAURATION</p><h1>Employés</h1><p>Organise l’équipe de salle, de cuisine, d’accueil et de plonge.</p></div><button className="primary-button" onClick={() => setSearchParams({ new: '1' })}><Icon name="plus" size={18}/>Ajouter un employé</button></header>
    {formOpen && <section className="panel restaurant-form-panel"><div className="panel-header"><div><p className="eyebrow">NOUVEL EMPLOYÉ</p><h2>Créer une fiche</h2></div><button className="secondary-button compact-button" onClick={() => setSearchParams({})}>Fermer</button></div><form className="restaurant-form-grid" onSubmit={createEmployee}><label>Prénom *<input autoFocus required value={form.firstName} onChange={(e) => setForm({ ...form, firstName: e.target.value })}/></label><label>Nom *<input required value={form.lastName} onChange={(e) => setForm({ ...form, lastName: e.target.value })}/></label><label>Poste<select value={form.roleCode} onChange={(e) => setForm({ ...form, roleCode: e.target.value as RestaurantEmployeeRole })}>{Object.entries(RESTAURANT_ROLE_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Heures hebdomadaires<input type="number" min="0" max="80" step="0.5" value={form.weeklyHours} onChange={(e) => setForm({ ...form, weeklyHours: e.target.value })}/></label><label>E-mail<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })}/></label><label>Téléphone<input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })}/></label><div className="form-actions full-field"><button className="secondary-button" type="button" onClick={() => setSearchParams({})}>Annuler</button><button className="primary-button" disabled={saving}>{saving ? 'Enregistrement…' : 'Enregistrer'}</button></div></form></section>}
    {error && <div className="error-message page-message">{error}</div>}{success && <div className="success-message page-message">{success}</div>}
    <section className="panel restaurant-list-panel"><div className="restaurant-toolbar"><div><p className="eyebrow">ÉQUIPE</p><h2>{rows.length} employé{rows.length > 1 ? 's' : ''}</h2></div><input type="search" placeholder="Nom, poste, e-mail…" value={query} onChange={(e) => setQuery(e.target.value)}/></div>{loading ? <div className="restaurant-empty">Chargement…</div> : filtered.length === 0 ? <div className="restaurant-empty"><Icon name="users" size={30}/><strong>Aucun employé</strong><span>Ajoute l’équipe avant de construire le planning.</span></div> : <div className="restaurant-card-list">{filtered.map((row) => <article className="restaurant-record-card" key={row.id}><span className="restaurant-record-icon"><Icon name="users" size={20}/></span><div className="restaurant-record-main"><strong>{row.first_name} {row.last_name}</strong><span>{RESTAURANT_ROLE_LABELS[row.role_code]} · {row.weekly_hours} h/semaine</span><small>{[row.email, row.phone].filter(Boolean).join(' · ') || 'Coordonnées à compléter'}</small></div>{row.linked_user_id ? <span className="restaurant-status-pill confirmed">Compte actif</span> : <span className="restaurant-status-pill pending">Sans accès</span>}<button className="secondary-button compact-button" onClick={() => void archive(row)}>Archiver</button></article>)}</div>}</section>
  </div>;
}
