import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Icon } from '../components/Icon';
import { organizationHasFeature } from '../config/planEntitlements';
import { useAuth } from '../contexts/AuthContext';
import { useOrganization } from '../contexts/OrganizationContext';
import { formatRestaurantDateTime, nullableRestaurantText, type RestaurantReservationRecord, type RestaurantReservationStatus, type RestaurantTableRecord } from '../features/restaurant/types';
import { supabase } from '../lib/supabase';

function toLocalInput(date: Date) { const shifted = new Date(date.getTime() - date.getTimezoneOffset() * 60000); return shifted.toISOString().slice(0, 16); }
function defaultDate() { const date = new Date(); date.setHours(date.getHours() + 2, 0, 0, 0); return toLocalInput(date); }
const emptyForm = { guestName: '', guestEmail: '', guestPhone: '', partySize: '2', reservationAt: defaultDate(), durationMinutes: '120', tableId: '', notes: '' };
const statusLabels: Record<RestaurantReservationStatus, string> = { pending: 'En attente', confirmed: 'Confirmée', seated: 'Installée', completed: 'Terminée', canceled: 'Annulée', no_show: 'Absente' };

export function RestaurantReservationsPage() {
  const { organization } = useOrganization(); const { user, demoMode } = useAuth(); const [searchParams, setSearchParams] = useSearchParams();
  const [rows, setRows] = useState<RestaurantReservationRecord[]>([]); const [tables, setTables] = useState<RestaurantTableRecord[]>([]); const [form, setForm] = useState(emptyForm); const [day, setDay] = useState(new Date().toISOString().slice(0, 10));
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const formOpen = searchParams.get('new') === '1';
  const hasOnline = Boolean(organization && organizationHasFeature(organization, 'restaurant_online_reservations'));

  async function load() { if (!organization) return; setLoading(true); setError(''); const start = new Date(`${day}T00:00:00`); const end = new Date(start); end.setDate(end.getDate() + 1); if (demoMode || !supabase) { setRows(JSON.parse(localStorage.getItem(`ncr-restaurant-reservations-${organization.id}`) || '[]')); setTables(JSON.parse(localStorage.getItem(`ncr-restaurant-tables-${organization.id}`) || '[]')); } else { const [reservationResult, tableResult] = await Promise.all([supabase.from('restaurant_reservations').select('*,restaurant_tables(name,area)').eq('organization_id', organization.id).gte('reservation_at', start.toISOString()).lt('reservation_at', end.toISOString()).order('reservation_at'), supabase.from('restaurant_tables').select('*').eq('organization_id', organization.id).eq('active', true).order('area').order('name')]); const firstError = reservationResult.error || tableResult.error; if (firstError) setError(firstError.message); setRows((reservationResult.data ?? []) as RestaurantReservationRecord[]); setTables((tableResult.data ?? []) as RestaurantTableRecord[]); } setLoading(false); }
  useEffect(() => { void load(); }, [organization?.id, demoMode, day]);

  async function createReservation(event: FormEvent) { event.preventDefault(); if (!organization || !user) return; setSaving(true); setError(''); setSuccess(''); const table = tables.find((row) => row.id === form.tableId); const payload = { organization_id: organization.id, table_id: form.tableId || null, source: 'manual', guest_name: form.guestName.trim(), guest_email: nullableRestaurantText(form.guestEmail)?.toLowerCase() ?? null, guest_phone: nullableRestaurantText(form.guestPhone), party_size: Math.max(1, Math.min(100, Number(form.partySize) || 1)), reservation_at: new Date(form.reservationAt).toISOString(), duration_minutes: Math.max(30, Math.min(360, Number(form.durationMinutes) || 120)), notes: nullableRestaurantText(form.notes), created_by: user.id }; try { let created: RestaurantReservationRecord; if (demoMode || !supabase) { created = { id: crypto.randomUUID(), ...payload, source: 'manual', status: 'confirmed', restaurant_tables: table ? { name: table.name, area: table.area } : null }; const next = [...rows, created].sort((a, b) => a.reservation_at.localeCompare(b.reservation_at)); localStorage.setItem(`ncr-restaurant-reservations-${organization.id}`, JSON.stringify(next)); } else { const { data, error: insertError } = await supabase.from('restaurant_reservations').insert(payload).select('*,restaurant_tables(name,area)').single(); if (insertError) throw insertError; created = data as RestaurantReservationRecord; } setRows((current) => [...current, created].sort((a, b) => a.reservation_at.localeCompare(b.reservation_at))); setForm(emptyForm); setSearchParams({}); setSuccess('La réservation a été créée.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Création impossible.'); } finally { setSaving(false); } }

  async function setStatus(row: RestaurantReservationRecord, status: RestaurantReservationStatus) { if (!organization) return; try { if (demoMode || !supabase) { const next = rows.map((item) => item.id === row.id ? { ...item, status } : item); localStorage.setItem(`ncr-restaurant-reservations-${organization.id}`, JSON.stringify(next)); setRows(next); } else { const { error: updateError } = await supabase.from('restaurant_reservations').update({ status }).eq('organization_id', organization.id).eq('id', row.id); if (updateError) throw updateError; setRows((current) => current.map((item) => item.id === row.id ? { ...item, status } : item)); } } catch (caught) { setError(caught instanceof Error ? caught.message : 'Mise à jour impossible.'); } }

  const activeRows = useMemo(() => rows.filter((row) => row.reservation_at.slice(0, 10) === day), [rows, day]); const covers = activeRows.filter((row) => !['canceled', 'no_show'].includes(row.status)).reduce((total, row) => total + row.party_size, 0);
  if (!organization) return null;
  return <div className="page restaurant-page"><header className="page-header"><div><p className="eyebrow">RESTAURATION</p><h1>Réservations</h1><p>Centralise les réservations internes et celles reçues depuis le lien public.</p></div><div className="header-actions">{hasOnline && <a className="secondary-button" href={`/r/${organization.slug}/reserver`} target="_blank" rel="noreferrer"><Icon name="eye" size={18}/>Page publique</a>}<button className="primary-button" onClick={() => setSearchParams({ new: '1' })}><Icon name="plus" size={18}/>Nouvelle réservation</button></div></header>
    {formOpen && <section className="panel restaurant-form-panel"><div className="panel-header"><div><p className="eyebrow">NOUVELLE RÉSERVATION</p><h2>Ajouter des clients</h2></div><button className="secondary-button compact-button" onClick={() => setSearchParams({})}>Fermer</button></div><form className="restaurant-form-grid" onSubmit={createReservation}><label>Nom *<input autoFocus required value={form.guestName} onChange={(e) => setForm({ ...form, guestName: e.target.value })}/></label><label>Nombre de personnes *<input type="number" min="1" max="100" required value={form.partySize} onChange={(e) => setForm({ ...form, partySize: e.target.value })}/></label><label>Date et heure *<input type="datetime-local" required value={form.reservationAt} onChange={(e) => setForm({ ...form, reservationAt: e.target.value })}/></label><label>Durée estimée<select value={form.durationMinutes} onChange={(e) => setForm({ ...form, durationMinutes: e.target.value })}><option value="60">1 h</option><option value="90">1 h 30</option><option value="120">2 h</option><option value="150">2 h 30</option><option value="180">3 h</option></select></label><label>E-mail<input type="email" value={form.guestEmail} onChange={(e) => setForm({ ...form, guestEmail: e.target.value })}/></label><label>Téléphone<input value={form.guestPhone} onChange={(e) => setForm({ ...form, guestPhone: e.target.value })}/></label><label className="full-field">Table<select value={form.tableId} onChange={(e) => setForm({ ...form, tableId: e.target.value })}><option value="">À attribuer plus tard</option>{tables.map((table) => <option key={table.id} value={table.id}>{table.name} · {table.area} · {table.capacity} places</option>)}</select></label><label className="full-field">Notes<textarea rows={3} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })}/></label><div className="form-actions full-field"><button type="button" className="secondary-button" onClick={() => setSearchParams({})}>Annuler</button><button className="primary-button" disabled={saving}>{saving ? 'Enregistrement…' : 'Enregistrer'}</button></div></form></section>}
    {error && <div className="error-message page-message">{error}</div>}{success && <div className="success-message page-message">{success}</div>}
    <section className="panel restaurant-list-panel"><div className="restaurant-toolbar"><div><p className="eyebrow">SERVICE</p><h2>{activeRows.length} réservation{activeRows.length > 1 ? 's' : ''} · {covers} couverts</h2></div><input type="date" value={day} onChange={(e) => setDay(e.target.value)}/></div>{loading ? <div className="restaurant-empty">Chargement…</div> : activeRows.length === 0 ? <div className="restaurant-empty"><Icon name="calendar" size={30}/><strong>Aucune réservation</strong><span>Ajoute une réservation ou partage la page publique.</span></div> : <div className="restaurant-card-list">{activeRows.map((row) => <article className="restaurant-record-card restaurant-reservation-card" key={row.id}><span className="restaurant-time-block">{new Intl.DateTimeFormat('fr-FR', { hour: '2-digit', minute: '2-digit' }).format(new Date(row.reservation_at))}</span><div className="restaurant-record-main"><strong>{row.guest_name} · {row.party_size} pers.</strong><span>{row.restaurant_tables?.name ? `${row.restaurant_tables.name} · ${row.restaurant_tables.area}` : 'Table à attribuer'} · source {row.source === 'online' ? 'en ligne' : 'interne'}</span><small>{[row.guest_phone, row.guest_email, row.notes].filter(Boolean).join(' · ') || 'Aucune précision'}</small></div><select className={`restaurant-status-select ${row.status}`} value={row.status} onChange={(e) => void setStatus(row, e.target.value as RestaurantReservationStatus)}>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></article>)}</div>}</section>
  </div>;
}
