import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Icon } from '../components/Icon';
import { useAuth } from '../contexts/AuthContext';
import { useOrganization } from '../contexts/OrganizationContext';
import { formatRestaurantDateTime, nullableRestaurantText, RESTAURANT_ROLE_LABELS, type RestaurantEmployeeRecord, type RestaurantShiftRecord } from '../features/restaurant/types';
import { supabase } from '../lib/supabase';

function toLocalInput(date: Date) { const shifted = new Date(date.getTime() - date.getTimezoneOffset() * 60000); return shifted.toISOString().slice(0, 16); }
function defaultStart() { const date = new Date(); date.setHours(date.getHours() + 1, 0, 0, 0); return toLocalInput(date); }
function defaultEnd() { const date = new Date(); date.setHours(date.getHours() + 5, 0, 0, 0); return toLocalInput(date); }

export function RestaurantPlanningPage() {
  const { organization } = useOrganization(); const { user, demoMode } = useAuth();
  const [rows, setRows] = useState<RestaurantShiftRecord[]>([]); const [employees, setEmployees] = useState<RestaurantEmployeeRecord[]>([]);
  const [employeeId, setEmployeeId] = useState(''); const [startsAt, setStartsAt] = useState(defaultStart); const [endsAt, setEndsAt] = useState(defaultEnd); const [position, setPosition] = useState(''); const [notes, setNotes] = useState('');
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');

  async function load() { if (!organization) return; setLoading(true); setError(''); const start = new Date(); start.setDate(start.getDate() - 1); const end = new Date(); end.setDate(end.getDate() + 15); if (demoMode || !supabase) { const employeeRows = JSON.parse(localStorage.getItem(`ncr-restaurant-employees-${organization.id}`) || '[]') as RestaurantEmployeeRecord[]; const shiftRows = JSON.parse(localStorage.getItem(`ncr-restaurant-shifts-${organization.id}`) || '[]') as RestaurantShiftRecord[]; setEmployees(employeeRows); setRows(shiftRows); } else { const [employeeResult, shiftResult] = await Promise.all([supabase.from('restaurant_employees').select('*').eq('organization_id', organization.id).eq('status', 'active').order('last_name'), supabase.from('restaurant_shifts').select('*,restaurant_employees(first_name,last_name,role_code)').eq('organization_id', organization.id).gte('starts_at', start.toISOString()).lt('starts_at', end.toISOString()).order('starts_at')]); const firstError = employeeResult.error || shiftResult.error; if (firstError) setError(firstError.message); setEmployees((employeeResult.data ?? []) as RestaurantEmployeeRecord[]); setRows((shiftResult.data ?? []) as RestaurantShiftRecord[]); } setLoading(false); }
  useEffect(() => { void load(); }, [organization?.id, demoMode]);

  async function createShift(event: FormEvent) { event.preventDefault(); if (!organization || !user || !employeeId) return; setSaving(true); setError(''); setSuccess(''); const payload = { organization_id: organization.id, employee_id: employeeId, starts_at: new Date(startsAt).toISOString(), ends_at: new Date(endsAt).toISOString(), position_label: nullableRestaurantText(position), notes: nullableRestaurantText(notes), created_by: user.id }; try { let created: RestaurantShiftRecord; if (demoMode || !supabase) { const employee = employees.find((item) => item.id === employeeId)!; created = { id: crypto.randomUUID(), ...payload, status: 'planned', restaurant_employees: employee }; const next = [...rows, created].sort((a, b) => a.starts_at.localeCompare(b.starts_at)); localStorage.setItem(`ncr-restaurant-shifts-${organization.id}`, JSON.stringify(next)); } else { const { data, error: insertError } = await supabase.from('restaurant_shifts').insert(payload).select('*,restaurant_employees(first_name,last_name,role_code)').single(); if (insertError) throw insertError; created = data as RestaurantShiftRecord; } setRows((current) => [...current, created].sort((a, b) => a.starts_at.localeCompare(b.starts_at))); setEmployeeId(''); setPosition(''); setNotes(''); setStartsAt(defaultStart()); setEndsAt(defaultEnd()); setSuccess('Le service a été planifié.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Planification impossible.'); } finally { setSaving(false); } }

  async function cancel(row: RestaurantShiftRecord) { if (!organization || !window.confirm('Annuler ce service ?')) return; try { if (demoMode || !supabase) { const next = rows.map((item) => item.id === row.id ? { ...item, status: 'canceled' as const } : item); localStorage.setItem(`ncr-restaurant-shifts-${organization.id}`, JSON.stringify(next)); setRows(next); } else { const { error: updateError } = await supabase.from('restaurant_shifts').update({ status: 'canceled' }).eq('organization_id', organization.id).eq('id', row.id); if (updateError) throw updateError; setRows((current) => current.map((item) => item.id === row.id ? { ...item, status: 'canceled' } : item)); } setSuccess('Le service a été annulé.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Annulation impossible.'); } }

  const grouped = useMemo(() => { const map = new Map<string, RestaurantShiftRecord[]>(); rows.forEach((row) => { const key = row.starts_at.slice(0, 10); map.set(key, [...(map.get(key) ?? []), row]); }); return [...map.entries()]; }, [rows]);
  if (!organization) return null;
  return <div className="page restaurant-page"><header className="page-header"><div><p className="eyebrow">RESTAURATION</p><h1>Planning équipe</h1><p>Construis les services en évitant les doubles affectations.</p></div></header>
    {error && <div className="error-message page-message">{error}</div>}{success && <div className="success-message page-message">{success}</div>}
    <section className="restaurant-two-column"><article className="panel restaurant-form-panel"><div className="panel-header"><div><p className="eyebrow">NOUVEAU SERVICE</p><h2>Planifier un employé</h2></div></div><form className="restaurant-form-grid" onSubmit={createShift}><label className="full-field">Employé *<select required value={employeeId} onChange={(e) => setEmployeeId(e.target.value)}><option value="">Sélectionner…</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.first_name} {employee.last_name} · {RESTAURANT_ROLE_LABELS[employee.role_code]}</option>)}</select></label><label>Début *<input type="datetime-local" required value={startsAt} onChange={(e) => setStartsAt(e.target.value)}/></label><label>Fin *<input type="datetime-local" required value={endsAt} onChange={(e) => setEndsAt(e.target.value)}/></label><label className="full-field">Poste sur ce service<input value={position} onChange={(e) => setPosition(e.target.value)} placeholder="Salle, cuisine chaude, bar…"/></label><label className="full-field">Notes<textarea rows={3} value={notes} onChange={(e) => setNotes(e.target.value)}/></label><button className="primary-button full-field" disabled={saving || employees.length === 0}>{saving ? 'Planification…' : 'Planifier le service'}</button></form></article>
      <article className="panel restaurant-summary-panel"><p className="eyebrow">PROCHAINS JOURS</p><h2>{rows.filter((row) => row.status !== 'canceled').length} service{rows.filter((row) => row.status !== 'canceled').length > 1 ? 's' : ''}</h2><div className="restaurant-summary-metrics"><div><span>Équipe active</span><strong>{employees.length}</strong></div><div><span>Heures planifiées</span><strong>{Math.round(rows.filter((row) => row.status !== 'canceled').reduce((total, row) => total + (new Date(row.ends_at).getTime() - new Date(row.starts_at).getTime()) / 3600000, 0))} h</strong></div></div></article></section>
    <section className="panel restaurant-list-panel"><div className="panel-header"><div><p className="eyebrow">CALENDRIER</p><h2>Services planifiés</h2></div></div>{loading ? <div className="restaurant-empty">Chargement…</div> : grouped.length === 0 ? <div className="restaurant-empty"><Icon name="calendar" size={30}/><strong>Aucun service planifié</strong></div> : <div className="restaurant-day-list">{grouped.map(([day, dayRows]) => <section key={day}><h3>{new Intl.DateTimeFormat('fr-FR', { weekday: 'long', day: '2-digit', month: 'long' }).format(new Date(`${day}T12:00:00`))}</h3><div className="restaurant-card-list">{dayRows.map((row) => <article className={`restaurant-record-card${row.status === 'canceled' ? ' is-muted' : ''}`} key={row.id}><span className="restaurant-record-icon"><Icon name="clock" size={20}/></span><div className="restaurant-record-main"><strong>{row.restaurant_employees?.first_name} {row.restaurant_employees?.last_name}</strong><span>{row.position_label || (row.restaurant_employees ? RESTAURANT_ROLE_LABELS[row.restaurant_employees.role_code] : 'Service')}</span><small>{formatRestaurantDateTime(row.starts_at)} → {new Intl.DateTimeFormat('fr-FR', { hour: '2-digit', minute: '2-digit' }).format(new Date(row.ends_at))}</small></div><span className={`restaurant-status-pill ${row.status}`}>{row.status === 'canceled' ? 'Annulé' : 'Planifié'}</span>{row.status !== 'canceled' && <button className="secondary-button compact-button" onClick={() => void cancel(row)}>Annuler</button>}</article>)}</div></section>)}</div>}</section>
  </div>;
}
