import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Icon } from '../components/Icon';
import { useAuth } from '../contexts/AuthContext';
import { useOrganization } from '../contexts/OrganizationContext';
import { restaurantErrorMessage, safeRestaurantStorageArray } from '../features/restaurant/runtime';
import { nullableRestaurantText, type RestaurantChecklistItemRecord, type RestaurantChecklistRunRecord, type RestaurantChecklistTemplateRecord, type RestaurantTemperatureRecord } from '../features/restaurant/types';
import { supabase } from '../lib/supabase';

const tempFormInitial = { equipment: 'Réfrigérateur principal', temperature: '4', minimum: '0', maximum: '4', notes: '' };
const checklistFormInitial = { name: 'Ouverture du restaurant', type: 'opening' as 'opening' | 'closing' | 'cleaning', items: 'Vérifier les chambres froides\nContrôler la propreté de la salle\nVérifier les sanitaires' };

export function RestaurantFoodSafetyPage() {
  const { organization } = useOrganization(); const { user, demoMode } = useAuth();
  const [temperatures, setTemperatures] = useState<RestaurantTemperatureRecord[]>([]); const [templates, setTemplates] = useState<RestaurantChecklistTemplateRecord[]>([]); const [runs, setRuns] = useState<RestaurantChecklistRunRecord[]>([]); const [checked, setChecked] = useState<Record<string, string[]>>({});
  const [tempForm, setTempForm] = useState(tempFormInitial); const [checklistForm, setChecklistForm] = useState(checklistFormInitial);
  const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');

  async function load() { if (!organization) return; setError(''); if (demoMode || !supabase) { setTemperatures(safeRestaurantStorageArray<RestaurantTemperatureRecord>(`ncr-restaurant-temperatures-${organization.id}`)); setTemplates(safeRestaurantStorageArray<RestaurantChecklistTemplateRecord>(`ncr-restaurant-checklists-${organization.id}`)); setRuns(safeRestaurantStorageArray<RestaurantChecklistRunRecord>(`ncr-restaurant-checklist-runs-${organization.id}`)); return; } const start = new Date(); start.setDate(start.getDate() - 7); const [tempResult, templateResult, runResult] = await Promise.all([supabase.from('restaurant_temperature_logs').select('*,restaurant_employees(first_name,last_name)').eq('organization_id', organization.id).gte('logged_at', start.toISOString()).order('logged_at', { ascending: false }), supabase.from('restaurant_checklist_templates').select('*,restaurant_checklist_items(*)').eq('organization_id', organization.id).eq('active', true).order('name'), supabase.from('restaurant_checklist_runs').select('*').eq('organization_id', organization.id).gte('completed_at', start.toISOString()).order('completed_at', { ascending: false })]); const firstError = tempResult.error || templateResult.error || runResult.error; if (firstError) setError(firstError.message); setTemperatures((tempResult.data ?? []) as RestaurantTemperatureRecord[]); setTemplates((templateResult.data ?? []) as RestaurantChecklistTemplateRecord[]); setRuns((runResult.data ?? []) as RestaurantChecklistRunRecord[]); }
  useEffect(() => { void load(); }, [organization?.id, demoMode]);

  async function addTemperature(event: FormEvent) { event.preventDefault(); if (!organization || !user) return; setSaving(true); setError(''); const temperature = Number(tempForm.temperature.replace(',', '.')); const minimum = nullableRestaurantText(tempForm.minimum) === null ? null : Number(tempForm.minimum.replace(',', '.')); const maximum = nullableRestaurantText(tempForm.maximum) === null ? null : Number(tempForm.maximum.replace(',', '.')); const compliant = (minimum === null || temperature >= minimum) && (maximum === null || temperature <= maximum); const payload = { organization_id: organization.id, equipment_name: tempForm.equipment.trim(), temperature_celsius: temperature, minimum_celsius: minimum, maximum_celsius: maximum, compliant, notes: nullableRestaurantText(tempForm.notes), logged_by: user.id }; try { let created: RestaurantTemperatureRecord; if (demoMode || !supabase) { created = { id: crypto.randomUUID(), ...payload, employee_id: null, logged_at: new Date().toISOString() }; const next = [created, ...temperatures]; localStorage.setItem(`ncr-restaurant-temperatures-${organization.id}`, JSON.stringify(next)); } else { const { data, error: insertError } = await supabase.from('restaurant_temperature_logs').insert(payload).select('*').single(); if (insertError) throw insertError; created = data as RestaurantTemperatureRecord; } setTemperatures((current) => [created, ...current]); setTempForm(tempFormInitial); setSuccess(compliant ? 'Le relevé conforme a été enregistré.' : 'Le relevé est enregistré avec une alerte de non-conformité.'); } catch (caught) { setError(restaurantErrorMessage(caught, 'Enregistrement impossible.')); } finally { setSaving(false); } }

  async function addChecklist(event: FormEvent) { event.preventDefault(); if (!organization || !user) return; const labels = checklistForm.items.split('\n').map((value) => value.trim()).filter(Boolean); if (!labels.length) return; setSaving(true); setError(''); try { let template: RestaurantChecklistTemplateRecord; if (demoMode || !supabase) { const id = crypto.randomUUID(); const items: RestaurantChecklistItemRecord[] = labels.map((label, index) => ({ id: crypto.randomUUID(), organization_id: organization.id, template_id: id, label, required: true, position: index })); template = { id, organization_id: organization.id, name: checklistForm.name.trim(), checklist_type: checklistForm.type, active: true, restaurant_checklist_items: items }; const next = [...templates, template]; localStorage.setItem(`ncr-restaurant-checklists-${organization.id}`, JSON.stringify(next)); } else { const { data: templateId, error: templateError } = await supabase.rpc('create_restaurant_checklist_template', { p_organization_id: organization.id, p_name: checklistForm.name.trim(), p_checklist_type: checklistForm.type, p_items: labels }); if (templateError) throw templateError; const { data, error: loadError } = await supabase.from('restaurant_checklist_templates').select('*,restaurant_checklist_items(*)').eq('organization_id', organization.id).eq('id', templateId).single(); if (loadError) throw loadError; template = data as RestaurantChecklistTemplateRecord; } setTemplates((current) => [...current, template]); setChecklistForm(checklistFormInitial); setSuccess('La checklist a été créée.'); } catch (caught) { setError(restaurantErrorMessage(caught, 'Création impossible.')); } finally { setSaving(false); } }


  async function completeChecklist(template: RestaurantChecklistTemplateRecord) {
    if (!organization || !user) return;
    const selected = checked[template.id] ?? [];
    const requiredIds = (template.restaurant_checklist_items ?? []).filter((item) => item.required).map((item) => item.id);
    if (requiredIds.some((id) => !selected.includes(id))) { setError('Toutes les tâches obligatoires doivent être cochées.'); return; }
    setSaving(true); setError('');
    const payload = { organization_id: organization.id, template_id: template.id, completed_item_ids: selected, status: 'completed', completed_by: user.id };
    try {
      let created: RestaurantChecklistRunRecord;
      if (demoMode || !supabase) { created = { id: crypto.randomUUID(), ...payload, status: 'completed', notes: null, completed_at: new Date().toISOString() }; const next = [created, ...runs]; localStorage.setItem(`ncr-restaurant-checklist-runs-${organization.id}`, JSON.stringify(next)); }
      else { const { data, error: insertError } = await supabase.from('restaurant_checklist_runs').insert(payload).select('*').single(); if (insertError) throw insertError; created = data as RestaurantChecklistRunRecord; }
      setRuns((current) => [created, ...current]); setChecked((current) => ({ ...current, [template.id]: [] })); setSuccess(`Checklist « ${template.name} » validée.`);
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Validation impossible.'); }
    finally { setSaving(false); }
  }

  const nonCompliant = useMemo(() => temperatures.filter((row) => !row.compliant), [temperatures]);
  if (!organization) return null;
  return <div className="page restaurant-page"><header className="page-header"><div><p className="eyebrow">RESTAURATION</p><h1>Hygiène & températures</h1><p>Trace les relevés, non-conformités et routines d’ouverture, fermeture ou nettoyage.</p></div></header>{error && <div className="error-message page-message">{error}</div>}{success && <div className="success-message page-message">{success}</div>}
    <section className="stats-grid"><article className="stat-card"><span className="stat-icon"><Icon name="clipboard" size={22}/></span><span>Relevés sur 7 jours</span><strong>{temperatures.length}</strong><small>enregistrements horodatés</small></article><article className="stat-card"><span className="stat-icon"><Icon name="alert" size={22}/></span><span>Non-conformités</span><strong>{nonCompliant.length}</strong><small>à traiter et documenter</small></article><article className="stat-card"><span className="stat-icon"><Icon name="check" size={22}/></span><span>Checklists actives</span><strong>{templates.length}</strong><small>procédures disponibles</small></article></section>
    <section className="restaurant-two-column"><article className="panel restaurant-form-panel"><div className="panel-header"><div><p className="eyebrow">NOUVEAU RELEVÉ</p><h2>Contrôle de température</h2></div></div><form className="restaurant-form-grid" onSubmit={addTemperature}><label className="full-field">Équipement *<input required value={tempForm.equipment} onChange={(e) => setTempForm({ ...tempForm, equipment: e.target.value })}/></label><label>Température relevée °C *<input required inputMode="decimal" value={tempForm.temperature} onChange={(e) => setTempForm({ ...tempForm, temperature: e.target.value })}/></label><label>Minimum autorisé °C<input inputMode="decimal" value={tempForm.minimum} onChange={(e) => setTempForm({ ...tempForm, minimum: e.target.value })}/></label><label>Maximum autorisé °C<input inputMode="decimal" value={tempForm.maximum} onChange={(e) => setTempForm({ ...tempForm, maximum: e.target.value })}/></label><label className="full-field">Observation<textarea rows={3} value={tempForm.notes} onChange={(e) => setTempForm({ ...tempForm, notes: e.target.value })}/></label><button className="primary-button full-field" disabled={saving}>{saving ? 'Enregistrement…' : 'Enregistrer le relevé'}</button></form></article>
      <article className="panel restaurant-form-panel"><div className="panel-header"><div><p className="eyebrow">PROCÉDURE</p><h2>Créer une checklist</h2></div></div><form className="restaurant-form-grid" onSubmit={addChecklist}><label>Nom *<input required value={checklistForm.name} onChange={(e) => setChecklistForm({ ...checklistForm, name: e.target.value })}/></label><label>Type<select value={checklistForm.type} onChange={(e) => setChecklistForm({ ...checklistForm, type: e.target.value as typeof checklistForm.type })}><option value="opening">Ouverture</option><option value="closing">Fermeture</option><option value="cleaning">Nettoyage</option></select></label><label className="full-field">Tâches, une par ligne<textarea rows={7} required value={checklistForm.items} onChange={(e) => setChecklistForm({ ...checklistForm, items: e.target.value })}/></label><button className="secondary-button full-field" disabled={saving}>{saving ? 'Création…' : 'Créer la checklist'}</button></form></article></section>
    <section className="restaurant-dashboard-grid"><article className="panel"><div className="panel-header"><div><p className="eyebrow">HISTORIQUE</p><h2>Derniers relevés</h2></div></div><div className="restaurant-card-list">{temperatures.slice(0, 12).map((row) => <article className="restaurant-record-card" key={row.id}><span className={`restaurant-record-icon ${row.compliant ? 'success' : 'danger'}`}><Icon name={row.compliant ? 'check' : 'alert'} size={20}/></span><div className="restaurant-record-main"><strong>{row.equipment_name} · {row.temperature_celsius} °C</strong><span>{row.compliant ? 'Conforme' : 'Non conforme'}{row.maximum_celsius !== null ? ` · maximum ${row.maximum_celsius} °C` : ''}</span><small>{new Intl.DateTimeFormat('fr-FR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(row.logged_at))}{row.notes ? ` · ${row.notes}` : ''}</small></div></article>)}{temperatures.length === 0 && <div className="restaurant-empty">Aucun relevé enregistré.</div>}</div></article><article className="panel"><div className="panel-header"><div><p className="eyebrow">CHECKLISTS</p><h2>Procédures actives</h2></div></div><div className="restaurant-checklist-list">{templates.map((template) => { const selected = checked[template.id] ?? []; const latest = runs.find((run) => run.template_id === template.id); return <article key={template.id}><strong>{template.name}</strong><span>{template.checklist_type === 'opening' ? 'Ouverture' : template.checklist_type === 'closing' ? 'Fermeture' : 'Nettoyage'} · {template.restaurant_checklist_items?.length ?? 0} tâches{latest ? ` · dernière validation ${new Intl.DateTimeFormat('fr-FR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(latest.completed_at))}` : ''}</span><div className="restaurant-checklist-items">{template.restaurant_checklist_items?.sort((a,b) => a.position-b.position).map((item) => <label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={(event) => setChecked((current) => ({ ...current, [template.id]: event.target.checked ? [...(current[template.id] ?? []), item.id] : (current[template.id] ?? []).filter((id) => id !== item.id) }))}/><span>{item.label}{item.required ? ' *' : ''}</span></label>)}</div><button className="secondary-button compact-button" disabled={saving || !template.restaurant_checklist_items?.length} onClick={() => void completeChecklist(template)}>Valider la checklist</button></article>; })}{templates.length === 0 && <div className="restaurant-empty">Aucune checklist.</div>}</div></article></section>
  </div>;
}
