import { FormEvent, useEffect, useState } from 'react';
import { Icon } from '../components/Icon';
import { useAuth } from '../contexts/AuthContext';
import { useOrganization } from '../contexts/OrganizationContext';
import type { RestaurantTableRecord } from '../features/restaurant/types';
import { supabase } from '../lib/supabase';

const emptyForm = { name: '', area: 'Salle principale', capacity: '2', positionX: '20', positionY: '20' };

export function RestaurantFloorPlanPage() {
  const { organization } = useOrganization(); const { user, demoMode } = useAuth();
  const [rows, setRows] = useState<RestaurantTableRecord[]>([]); const [form, setForm] = useState(emptyForm); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  async function load() { if (!organization) return; if (demoMode || !supabase) setRows(JSON.parse(localStorage.getItem(`ncr-restaurant-tables-${organization.id}`) || '[]')); else { const { data, error: loadError } = await supabase.from('restaurant_tables').select('*').eq('organization_id', organization.id).eq('active', true).order('area').order('name'); if (loadError) setError(loadError.message); else setRows((data ?? []) as RestaurantTableRecord[]); } }
  useEffect(() => { void load(); }, [organization?.id, demoMode]);

  async function createTable(event: FormEvent) { event.preventDefault(); if (!organization || !user) return; setSaving(true); setError(''); const payload = { organization_id: organization.id, name: form.name.trim(), area: form.area.trim(), capacity: Math.max(1, Math.min(30, Number(form.capacity) || 2)), position_x: Math.max(0, Math.min(90, Number(form.positionX) || 0)), position_y: Math.max(0, Math.min(90, Number(form.positionY) || 0)), created_by: user.id }; try { let created: RestaurantTableRecord; if (demoMode || !supabase) { created = { id: crypto.randomUUID(), ...payload, active: true }; localStorage.setItem(`ncr-restaurant-tables-${organization.id}`, JSON.stringify([...rows, created])); } else { const { data, error: insertError } = await supabase.from('restaurant_tables').insert(payload).select('*').single(); if (insertError) throw insertError; created = data as RestaurantTableRecord; } setRows((current) => [...current, created]); setForm(emptyForm); setSuccess('La table a été ajoutée au plan.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Création impossible.'); } finally { setSaving(false); } }

  async function remove(row: RestaurantTableRecord) { if (!organization || !window.confirm(`Retirer ${row.name} du plan ?`)) return; try { if (demoMode || !supabase) { const next = rows.filter((item) => item.id !== row.id); localStorage.setItem(`ncr-restaurant-tables-${organization.id}`, JSON.stringify(next)); setRows(next); } else { const { error: updateError } = await supabase.from('restaurant_tables').update({ active: false }).eq('organization_id', organization.id).eq('id', row.id); if (updateError) throw updateError; setRows((current) => current.filter((item) => item.id !== row.id)); } } catch (caught) { setError(caught instanceof Error ? caught.message : 'Suppression impossible.'); } }

  if (!organization) return null;
  return <div className="page restaurant-page"><header className="page-header"><div><p className="eyebrow">RESTAURATION</p><h1>Plan de salle</h1><p>Crée les zones et tables utilisées pour l’attribution des réservations.</p></div></header>{error && <div className="error-message page-message">{error}</div>}{success && <div className="success-message page-message">{success}</div>}
    <section className="restaurant-floor-layout"><article className="panel restaurant-floor-canvas"><div className="panel-header"><div><p className="eyebrow">SALLE</p><h2>{rows.length} table{rows.length > 1 ? 's' : ''} · {rows.reduce((total, row) => total + row.capacity, 0)} couverts</h2></div></div><div className="restaurant-room-map">{rows.length === 0 ? <div className="restaurant-empty"><Icon name="map" size={30}/><strong>Plan vide</strong><span>Ajoute les premières tables.</span></div> : rows.map((row) => <button type="button" key={row.id} className="restaurant-table-node" style={{ left: `${row.position_x}%`, top: `${row.position_y}%` }} title={`${row.area} · ${row.capacity} places`} onDoubleClick={() => void remove(row)}><strong>{row.name}</strong><span>{row.capacity}</span></button>)}</div><small className="restaurant-floor-help">Double-clique sur une table pour la retirer. Les positions servent de repères visuels.</small></article>
      <article className="panel restaurant-form-panel"><div className="panel-header"><div><p className="eyebrow">NOUVELLE TABLE</p><h2>Ajouter au plan</h2></div></div><form className="restaurant-form-grid" onSubmit={createTable}><label>Nom *<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Table 1"/></label><label>Zone *<input required value={form.area} onChange={(e) => setForm({ ...form, area: e.target.value })}/></label><label>Capacité<input type="number" min="1" max="30" value={form.capacity} onChange={(e) => setForm({ ...form, capacity: e.target.value })}/></label><label>Position horizontale %<input type="number" min="0" max="90" value={form.positionX} onChange={(e) => setForm({ ...form, positionX: e.target.value })}/></label><label className="full-field">Position verticale %<input type="number" min="0" max="90" value={form.positionY} onChange={(e) => setForm({ ...form, positionY: e.target.value })}/></label><button className="primary-button full-field" disabled={saving}>{saving ? 'Ajout…' : 'Ajouter la table'}</button></form></article></section>
  </div>;
}
