import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Icon } from '../components/Icon';
import { organizationHasFeature } from '../config/planEntitlements';
import { useAuth } from '../contexts/AuthContext';
import { useOrganization } from '../contexts/OrganizationContext';
import { formatRestaurantMoney, nullableRestaurantText, RESTAURANT_ALLERGENS, type RestaurantMenuCategoryRecord, type RestaurantMenuItemRecord } from '../features/restaurant/types';
import { supabase } from '../lib/supabase';

const emptyItem = { categoryId: '', name: '', descriptionFr: '', descriptionEn: '', descriptionEs: '', descriptionIt: '', price: '', cost: '', allergens: [] as string[], vegetarian: false, vegan: false, featured: false };

export function RestaurantMenuPage() {
  const { organization } = useOrganization(); const { user, demoMode } = useAuth();
  const [categories, setCategories] = useState<RestaurantMenuCategoryRecord[]>([]); const [items, setItems] = useState<RestaurantMenuItemRecord[]>([]); const [categoryName, setCategoryName] = useState(''); const [form, setForm] = useState(emptyItem); const [query, setQuery] = useState('');
  const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const hasQr = Boolean(organization && organizationHasFeature(organization, 'restaurant_multilingual_qr_menu')); const hasCost = Boolean(organization && organizationHasFeature(organization, 'restaurant_food_cost')); const canViewCosts = hasCost && ['owner', 'admin'].includes(organization?.role ?? 'viewer');

  async function load() { if (!organization) return; setError(''); if (demoMode || !supabase) { setCategories(JSON.parse(localStorage.getItem(`ncr-restaurant-categories-${organization.id}`) || '[]')); setItems((JSON.parse(localStorage.getItem(`ncr-restaurant-menu-${organization.id}`) || '[]') as RestaurantMenuItemRecord[]).map((row) => ({ ...row, cost_cents: Number(row.cost_cents ?? 0) }))); return; } const [categoryResult, itemResult, costResult] = await Promise.all([supabase.from('restaurant_menu_categories').select('*').eq('organization_id', organization.id).eq('active', true).order('position'), supabase.from('restaurant_menu_items').select('*,restaurant_menu_categories(name)').eq('organization_id', organization.id).order('name'), canViewCosts ? supabase.from('restaurant_menu_costs').select('menu_item_id,cost_cents').eq('organization_id', organization.id) : Promise.resolve({ data: [], error: null })]); const firstError = categoryResult.error || itemResult.error || costResult.error; if (firstError) setError(firstError.message); const costs = new Map((costResult.data ?? []).map((row: { menu_item_id: string; cost_cents: number }) => [row.menu_item_id, row.cost_cents])); setCategories((categoryResult.data ?? []) as RestaurantMenuCategoryRecord[]); setItems(((itemResult.data ?? []) as RestaurantMenuItemRecord[]).map((row) => ({ ...row, cost_cents: Number(costs.get(row.id) ?? 0) }))); }
  useEffect(() => { void load(); }, [organization?.id, demoMode]);

  async function addCategory(event: FormEvent) { event.preventDefault(); if (!organization || !user || !categoryName.trim()) return; setSaving(true); try { let created: RestaurantMenuCategoryRecord; const payload = { organization_id: organization.id, name: categoryName.trim(), position: categories.length, created_by: user.id }; if (demoMode || !supabase) { created = { id: crypto.randomUUID(), ...payload, active: true }; localStorage.setItem(`ncr-restaurant-categories-${organization.id}`, JSON.stringify([...categories, created])); } else { const { data, error: insertError } = await supabase.from('restaurant_menu_categories').insert(payload).select('*').single(); if (insertError) throw insertError; created = data as RestaurantMenuCategoryRecord; } setCategories((current) => [...current, created]); setCategoryName(''); setSuccess('La catégorie a été ajoutée.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Création impossible.'); } finally { setSaving(false); } }

  async function addItem(event: FormEvent) { event.preventDefault(); if (!organization || !user || !form.categoryId || !form.name.trim()) return; setSaving(true); setError(''); setSuccess(''); const category = categories.find((row) => row.id === form.categoryId); const payload = { organization_id: organization.id, category_id: form.categoryId, name: form.name.trim(), description_fr: nullableRestaurantText(form.descriptionFr), description_en: hasQr ? nullableRestaurantText(form.descriptionEn) : null, description_es: hasQr ? nullableRestaurantText(form.descriptionEs) : null, description_it: hasQr ? nullableRestaurantText(form.descriptionIt) : null, price_cents: Math.max(0, Math.round(Number(form.price.replace(',', '.')) * 100)), allergens: form.allergens, vegetarian: form.vegetarian, vegan: form.vegan, featured: form.featured, created_by: user.id }; try { let created: RestaurantMenuItemRecord; if (demoMode || !supabase) { created = { id: crypto.randomUUID(), ...payload, cost_cents: canViewCosts ? Math.max(0, Math.round(Number(form.cost.replace(',', '.')) * 100)) : 0, available: true, image_url: null, restaurant_menu_categories: category ? { name: category.name } : null }; localStorage.setItem(`ncr-restaurant-menu-${organization.id}`, JSON.stringify([...items, created])); } else { const { data, error: insertError } = await supabase.from('restaurant_menu_items').insert(payload).select('*,restaurant_menu_categories(name)').single(); if (insertError) throw insertError; const costCents = canViewCosts ? Math.max(0, Math.round(Number(form.cost.replace(',', '.')) * 100)) : 0; if (canViewCosts) { const { error: costError } = await supabase.from('restaurant_menu_costs').upsert({ organization_id: organization.id, menu_item_id: data.id, cost_cents: costCents, created_by: user.id }, { onConflict: 'organization_id,menu_item_id' }); if (costError) throw costError; } created = { ...(data as RestaurantMenuItemRecord), cost_cents: costCents }; } setItems((current) => [...current, created]); setForm(emptyItem); setSuccess('Le plat a été ajouté à la carte.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Création impossible.'); } finally { setSaving(false); } }

  async function toggleAvailability(row: RestaurantMenuItemRecord) { if (!organization) return; const available = !row.available; try { if (demoMode || !supabase) { const next = items.map((item) => item.id === row.id ? { ...item, available } : item); localStorage.setItem(`ncr-restaurant-menu-${organization.id}`, JSON.stringify(next)); setItems(next); } else { const { error: updateError } = await supabase.from('restaurant_menu_items').update({ available }).eq('organization_id', organization.id).eq('id', row.id); if (updateError) throw updateError; setItems((current) => current.map((item) => item.id === row.id ? { ...item, available } : item)); } } catch (caught) { setError(caught instanceof Error ? caught.message : 'Modification impossible.'); } }

  const filtered = useMemo(() => { const needle = query.trim().toLowerCase(); return needle ? items.filter((row) => `${row.name} ${row.restaurant_menu_categories?.name ?? ''} ${row.allergens.join(' ')}`.toLowerCase().includes(needle)) : items; }, [items, query]);
  if (!organization) return null;
  return <div className="page restaurant-page"><header className="page-header"><div><p className="eyebrow">RESTAURATION</p><h1>Carte & menus</h1><p>Gère les plats, prix, allergènes, disponibilités et traductions.</p></div>{hasQr && <a className="secondary-button" href={`/r/${organization.slug}/menu`} target="_blank" rel="noreferrer"><Icon name="eye" size={18}/>Voir le menu public</a>}</header>
    {error && <div className="error-message page-message">{error}</div>}{success && <div className="success-message page-message">{success}</div>}
    <section className="restaurant-menu-layout"><article className="panel restaurant-form-panel"><div className="panel-header"><div><p className="eyebrow">CATÉGORIES</p><h2>Structurer la carte</h2></div></div><form className="restaurant-inline-form" onSubmit={addCategory}><input required value={categoryName} onChange={(e) => setCategoryName(e.target.value)} placeholder="Entrées, plats, desserts…"/><button className="secondary-button" disabled={saving}>Ajouter</button></form><div className="restaurant-chip-list">{categories.map((row) => <span key={row.id}>{row.name}</span>)}</div></article>
      <article className="panel restaurant-form-panel restaurant-menu-form"><div className="panel-header"><div><p className="eyebrow">NOUVEAU PLAT</p><h2>Ajouter à la carte</h2></div></div><form className="restaurant-form-grid" onSubmit={addItem}><label>Catégorie *<select required value={form.categoryId} onChange={(e) => setForm({ ...form, categoryId: e.target.value })}><option value="">Sélectionner…</option>{categories.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Nom *<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/></label><label>Prix TTC (€) *<input required inputMode="decimal" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })}/></label>{canViewCosts && <label>Coût matière (€)<input inputMode="decimal" value={form.cost} onChange={(e) => setForm({ ...form, cost: e.target.value })}/></label>}<label className="full-field">Description française<textarea rows={2} value={form.descriptionFr} onChange={(e) => setForm({ ...form, descriptionFr: e.target.value })}/></label>{hasQr && <><label>Description anglaise<textarea rows={2} value={form.descriptionEn} onChange={(e) => setForm({ ...form, descriptionEn: e.target.value })}/></label><label>Description espagnole<textarea rows={2} value={form.descriptionEs} onChange={(e) => setForm({ ...form, descriptionEs: e.target.value })}/></label><label className="full-field">Description italienne<textarea rows={2} value={form.descriptionIt} onChange={(e) => setForm({ ...form, descriptionIt: e.target.value })}/></label></>}<fieldset className="full-field restaurant-allergen-field"><legend>Allergènes</legend><div>{RESTAURANT_ALLERGENS.map((allergen) => <label key={allergen}><input type="checkbox" checked={form.allergens.includes(allergen)} onChange={(e) => setForm({ ...form, allergens: e.target.checked ? [...form.allergens, allergen] : form.allergens.filter((value) => value !== allergen) })}/>{allergen}</label>)}</div></fieldset><div className="full-field restaurant-switch-row"><label><input type="checkbox" checked={form.vegetarian} onChange={(e) => setForm({ ...form, vegetarian: e.target.checked })}/>Végétarien</label><label><input type="checkbox" checked={form.vegan} onChange={(e) => setForm({ ...form, vegan: e.target.checked })}/>Végan</label><label><input type="checkbox" checked={form.featured} onChange={(e) => setForm({ ...form, featured: e.target.checked })}/>À la une</label></div><button className="primary-button full-field" disabled={saving || categories.length === 0}>{saving ? 'Enregistrement…' : 'Ajouter le plat'}</button></form></article></section>
    <section className="panel restaurant-list-panel"><div className="restaurant-toolbar"><div><p className="eyebrow">CARTE ACTIVE</p><h2>{items.length} référence{items.length > 1 ? 's' : ''}</h2></div><input type="search" placeholder="Plat, catégorie, allergène…" value={query} onChange={(e) => setQuery(e.target.value)}/></div>{filtered.length === 0 ? <div className="restaurant-empty"><Icon name="utensils" size={30}/><strong>Aucun plat</strong><span>Crée une catégorie puis ajoute ta première référence.</span></div> : <div className="restaurant-menu-card-grid">{filtered.map((row) => { const margin = row.price_cents ? Math.round((row.price_cents - row.cost_cents) / row.price_cents * 100) : 0; return <article className={`restaurant-menu-card${row.available ? '' : ' unavailable'}`} key={row.id}><div><span className="restaurant-menu-category">{row.restaurant_menu_categories?.name || 'Sans catégorie'}</span><h3>{row.name}</h3><p>{row.description_fr || 'Description à compléter'}</p></div><div className="restaurant-menu-tags">{row.vegetarian && <span>Végétarien</span>}{row.vegan && <span>Végan</span>}{row.allergens.slice(0, 3).map((value) => <span key={value} className="warning">{value}</span>)}</div><footer><div><strong>{formatRestaurantMoney(row.price_cents)}</strong>{canViewCosts && <small>Marge théorique {margin} %</small>}</div><button className={`secondary-button compact-button${row.available ? '' : ' danger'}`} onClick={() => void toggleAvailability(row)}>{row.available ? 'Disponible' : 'En rupture'}</button></footer></article>; })}</div>}</section>
  </div>;
}
