import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react';
import { Icon } from '../components/Icon';
import { useAuth } from '../contexts/AuthContext';
import { useOrganization } from '../contexts/OrganizationContext';
import { formatSecurityDate, securityPersonName, type SecurityAgentRecord, type SecurityPatrolPointRecord, type SecurityPatrolRecord, type SecuritySiteRecord } from '../features/security/types';
import { supabase } from '../lib/supabase';

type PointForm={siteId:string;label:string;sequence:string;instructions:string};
const emptyPoint:PointForm={siteId:'',label:'',sequence:'1',instructions:''};

export function SecurityPatrolsPage(){
 const {organization}=useOrganization();const {user,demoMode}=useAuth();const canManage=['owner','admin','manager'].includes(organization?.role??'viewer');
 const [sites,setSites]=useState<SecuritySiteRecord[]>([]);const [agents,setAgents]=useState<SecurityAgentRecord[]>([]);const [points,setPoints]=useState<SecurityPatrolPointRecord[]>([]);const [patrols,setPatrols]=useState<SecurityPatrolRecord[]>([]);
 const [form,setForm]=useState<PointForm>(emptyPoint);const [open,setOpen]=useState(false);const [selectedSite,setSelectedSite]=useState('');const [current,setCurrent]=useState<SecurityPatrolRecord|null>(null);const [manualCode,setManualCode]=useState('');const [qrPreview,setQrPreview]=useState<{point:SecurityPatrolPointRecord;url:string}|null>(null);
 const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');
 async function load(){if(!organization)return;setLoading(true);setError('');if(demoMode||!supabase){setSites(JSON.parse(localStorage.getItem(`ncr-suite-security-sites-${organization.id}`)||'[]'));setAgents(JSON.parse(localStorage.getItem(`ncr-suite-security-agents-${organization.id}`)||'[]'));setPoints(JSON.parse(localStorage.getItem(`ncr-suite-security-points-${organization.id}`)||'[]'));const stored=JSON.parse(localStorage.getItem(`ncr-suite-security-patrols-${organization.id}`)||'[]') as SecurityPatrolRecord[];setPatrols(stored);setCurrent(stored.find(p=>p.status==='in_progress')||null);setLoading(false);return;}
  const [s,a,p,r]=await Promise.all([
   supabase.from('security_sites').select('id,organization_id,client_id,name,code,address,postal_code,city,contact_name,contact_phone,hourly_rate_cents,color_hex,timezone,notes,status,created_at,security_clients(company_name)').eq('organization_id',organization.id).eq('status','active').order('name'),
   supabase.from('security_agents').select('id,organization_id,first_name,last_name,employee_number,email,phone,contract_type,weekly_hours,notes,status,linked_user_id,created_at').eq('organization_id',organization.id).eq('status','active').order('last_name'),
   supabase.from('security_patrol_points').select('id,organization_id,site_id,label,qr_code,sequence_number,instructions,status,created_at,security_sites(name,color_hex)').eq('organization_id',organization.id).eq('status','active').order('site_id').order('sequence_number'),
   supabase.from('security_patrols').select('id,organization_id,site_id,agent_id,started_at,completed_at,status,notes,created_at,security_sites(name,color_hex),security_agents(first_name,last_name),security_patrol_scans(id,organization_id,patrol_id,point_id,scanned_at,status,security_patrol_points(label,sequence_number))').eq('organization_id',organization.id).order('started_at',{ascending:false}).limit(50)]);
  const e=s.error||a.error||p.error||r.error;if(e)setError(`Chargement impossible : ${e.message}`);else{setSites((s.data??[]) as unknown as SecuritySiteRecord[]);setAgents((a.data??[]) as SecurityAgentRecord[]);setPoints((p.data??[]) as unknown as SecurityPatrolPointRecord[]);const rows=(r.data??[]) as unknown as SecurityPatrolRecord[];setPatrols(rows);setCurrent(rows.find(x=>x.status==='in_progress')||null);}setLoading(false);
 }
 useEffect(()=>{void load();},[organization?.id,demoMode]);useEffect(()=>{const id=sites[0]?.id||'';setForm(v=>({...v,siteId:v.siteId||id}));setSelectedSite(v=>v||id);},[sites]);
 async function createPoint(e:FormEvent){e.preventDefault();if(!organization||!user||!canManage)return;setSaving(true);setError('');const code=`NCRSEC:${organization.id}:${crypto.randomUUID()}`;const payload={organization_id:organization.id,site_id:form.siteId,label:form.label.trim(),qr_code:code,sequence_number:Math.max(1,Number(form.sequence)||1),instructions:form.instructions.trim()||null,created_by:user.id};try{if(demoMode||!supabase){const site=sites.find(s=>s.id===form.siteId);const created={id:crypto.randomUUID(),...payload,status:'active',created_at:new Date().toISOString(),security_sites:site?{name:site.name,color_hex:site.color_hex}:null};const next=[...points,created];localStorage.setItem(`ncr-suite-security-points-${organization.id}`,JSON.stringify(next));setPoints(next as SecurityPatrolPointRecord[]);}else{const{error:e}=await supabase.from('security_patrol_points').insert(payload);if(e)throw e;await load();}setForm({...emptyPoint,siteId:sites[0]?.id||''});setOpen(false);setSuccess('Le point de ronde QR a été créé.');}catch(c){setError(`Création impossible : ${c instanceof Error?c.message:'erreur inconnue'}`);}finally{setSaving(false);}}
 async function preview(point:SecurityPatrolPointRecord){try{const {default:QRCode}=await import('qrcode');const url=await QRCode.toDataURL(point.qr_code,{width:520,margin:2,errorCorrectionLevel:'H'});setQrPreview({point,url});}catch(c){setError(c instanceof Error?c.message:'QR impossible');}}
 function downloadQr(){if(!qrPreview)return;const a=document.createElement('a');a.href=qrPreview.url;a.download=`qr-${qrPreview.point.label.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.png`;document.body.appendChild(a);a.click();a.remove();}
 async function start(){if(!organization||!selectedSite)return;setSaving(true);setError('');try{if(demoMode||!supabase){const agent=agents[0];if(!agent)throw new Error('Aucun agent disponible.');const created={id:crypto.randomUUID(),organization_id:organization.id,site_id:selectedSite,agent_id:agent.id,started_at:new Date().toISOString(),completed_at:null,status:'in_progress',notes:null,created_at:new Date().toISOString(),security_sites:{name:sites.find(s=>s.id===selectedSite)?.name||'Site'},security_agents:{first_name:agent.first_name,last_name:agent.last_name},security_patrol_scans:[]};const next=[created,...patrols];localStorage.setItem(`ncr-suite-security-patrols-${organization.id}`,JSON.stringify(next));setPatrols(next as SecurityPatrolRecord[]);setCurrent(created as SecurityPatrolRecord);}else{const{data,error:e}=await supabase.rpc('start_security_patrol',{p_organization_id:organization.id,p_site_id:selectedSite});if(e)throw e;await load();setSuccess(`Ronde démarrée (${data}).`);} }catch(c){setError(`Démarrage impossible : ${c instanceof Error?c.message:'erreur inconnue'}`);}finally{setSaving(false);}}
 async function recordCode(code:string){if(!organization||!current||!code.trim())return;setSaving(true);setError('');try{if(demoMode||!supabase){const point=points.find(p=>p.qr_code===code.trim()&&p.site_id===current.site_id);if(!point)throw new Error('Point QR inconnu.');setCurrent({...current,security_patrol_scans:[...(current.security_patrol_scans||[]),{id:crypto.randomUUID(),organization_id:organization.id,patrol_id:current.id,point_id:point.id,scanned_at:new Date().toISOString(),status:'valid',security_patrol_points:{label:point.label,sequence_number:point.sequence_number}}]});}else{const{data,error:e}=await supabase.rpc('record_security_patrol_scan',{p_organization_id:organization.id,p_patrol_id:current.id,p_qr_code:code.trim()});if(e)throw e;setSuccess(`Point validé : ${data?.[0]?.point_label||'OK'}`);await load();}setManualCode('');}catch(c){setError(`Scan impossible : ${c instanceof Error?c.message:'erreur inconnue'}`);}finally{setSaving(false);}}
 async function scanImage(e:ChangeEvent<HTMLInputElement>){
  const file=e.target.files?.[0];e.target.value='';if(!file)return;
  setSaving(true);setError('');
  try{
   let code='';
   const Detector=(window as Window & {BarcodeDetector?:new(options:{formats:string[]})=>{detect:(source:ImageBitmap)=>Promise<Array<{rawValue?:string}>>}}).BarcodeDetector;
   if(Detector&&'createImageBitmap'in window){
    const bitmap=await createImageBitmap(file);
    try{const result=await new Detector({formats:['qr_code']}).detect(bitmap);code=result?.[0]?.rawValue||'';}finally{bitmap.close();}
   }
   if(!code){
    const {default:jsQR}=await import('jsqr');
    const objectUrl=URL.createObjectURL(file);
    try{
     const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('Image illisible.'));img.src=objectUrl;});
     const maxSide=1800;const ratio=Math.min(1,maxSide/Math.max(image.naturalWidth,image.naturalHeight));
     const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*ratio));canvas.height=Math.max(1,Math.round(image.naturalHeight*ratio));
     const context=canvas.getContext('2d',{willReadFrequently:true});if(!context)throw new Error('Lecture de l’image indisponible.');
     context.drawImage(image,0,0,canvas.width,canvas.height);
     const pixels=context.getImageData(0,0,canvas.width,canvas.height);
     code=jsQR(pixels.data,pixels.width,pixels.height,{inversionAttempts:'attemptBoth'})?.data||'';
    }finally{URL.revokeObjectURL(objectUrl);}
   }
   if(!code)throw new Error('Aucun QR code détecté. Rapproche-toi du QR et reprends une photo nette.');
   await recordCode(code);
  }catch(c){setError(`Lecture QR impossible : ${c instanceof Error?c.message:'erreur inconnue'}`);}finally{setSaving(false);}
 }
 async function complete(){if(!organization||!current)return;setSaving(true);setError('');try{if(demoMode||!supabase){setPatrols(v=>v.map(p=>p.id===current.id?{...p,status:'completed',completed_at:new Date().toISOString()}:p));setCurrent(null);}else{const{error:e}=await supabase.rpc('complete_security_patrol',{p_organization_id:organization.id,p_patrol_id:current.id,p_notes:null});if(e)throw e;await load();}setSuccess('Ronde terminée et enregistrée.');}catch(c){setError(`Clôture impossible : ${c instanceof Error?c.message:'erreur inconnue'}`);}finally{setSaving(false);}}
 const currentPoints=useMemo(()=>points.filter(p=>p.site_id===current?.site_id),[points,current]);const scannedIds=new Set((current?.security_patrol_scans||[]).map(s=>s.point_id));
 if(!organization)return null;return <div className="page security-page"><header className="page-header"><div><p className="eyebrow">SÉCURITÉ PRIVÉE</p><h1>Rondes QR</h1><p>Crée les points de passage, imprime leurs QR codes et certifie chaque ronde sur le terrain.</p></div>{canManage&&<button className="primary-button" onClick={()=>setOpen(true)}><Icon name="plus" size={18}/>Ajouter un point QR</button>}</header>
 {open&&canManage&&<section className="panel security-form-panel"><div className="panel-header"><div><p className="eyebrow">POINT DE RONDE</p><h2>Créer un QR code</h2></div><button className="secondary-button compact-button" onClick={()=>setOpen(false)}>Fermer</button></div><form className="security-form-grid" onSubmit={createPoint}><label>Site *<select value={form.siteId} onChange={e=>setForm({...form,siteId:e.target.value})}>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Ordre<input type="number" min="1" value={form.sequence} onChange={e=>setForm({...form,sequence:e.target.value})}/></label><label className="full-field">Nom du point *<input required placeholder="Entrée principale, local technique…" value={form.label} onChange={e=>setForm({...form,label:e.target.value})}/></label><label className="full-field">Instruction<textarea rows={3} value={form.instructions} onChange={e=>setForm({...form,instructions:e.target.value})}/></label><div className="form-actions full-field"><button className="primary-button" disabled={saving}>Créer le QR</button></div></form></section>}
 {qrPreview&&<section className="panel security-qr-preview"><div><p className="eyebrow">QR À IMPRIMER</p><h2>{qrPreview.point.label}</h2><p>{qrPreview.point.security_sites?.name}</p><img src={qrPreview.url} alt={`QR ${qrPreview.point.label}`}/><code>{qrPreview.point.qr_code}</code><div className="form-actions"><button className="secondary-button" onClick={()=>setQrPreview(null)}>Fermer</button><button className="primary-button" onClick={downloadQr}>Télécharger le QR</button></div></div></section>}
 {error&&<div className="error-message page-message">{error}</div>}{success&&<div className="success-message page-message">{success}</div>}
 <section className="security-patrol-layout"><div className="panel security-patrol-action"><div className="panel-header"><div><p className="eyebrow">RONDE TERRAIN</p><h2>{current?'Ronde en cours':'Démarrer une ronde'}</h2></div>{current&&<span className="security-status-pill active">En cours</span>}</div>{!current?<><label className="security-field-label">Site<select value={selectedSite} onChange={e=>setSelectedSite(e.target.value)}>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button className="primary-button wide-button" disabled={!selectedSite||saving} onClick={()=>void start()}>Démarrer la ronde</button></>:<><div className="security-patrol-progress"><strong>{scannedIds.size}/{currentPoints.length}</strong><span>points validés</span></div><div className="security-point-checklist">{currentPoints.map(p=><article className={scannedIds.has(p.id)?'done':''} key={p.id}><span>{p.sequence_number}</span><div><strong>{p.label}</strong><small>{p.instructions||'Scanner le QR placé sur ce point.'}</small></div><Icon name={scannedIds.has(p.id)?'check':'map'} size={19}/></article>)}</div><label className="primary-button security-scan-button">Scanner un QR<input type="file" accept="image/*" capture="environment" onChange={scanImage}/></label><div className="security-manual-scan"><input placeholder="Code QR manuel" value={manualCode} onChange={e=>setManualCode(e.target.value)}/><button className="secondary-button" disabled={!manualCode||saving} onClick={()=>void recordCode(manualCode)}>Valider</button></div><button className="primary-button wide-button" disabled={saving||scannedIds.size<currentPoints.length} onClick={()=>void complete()}>Terminer la ronde</button></>}</div>
 <div className="panel security-list-panel"><div className="panel-header"><div><p className="eyebrow">POINTS CONFIGURÉS</p><h2>{points.length} point{points.length>1?'s':''}</h2></div></div>{loading?<div className="security-empty">Chargement…</div>:points.length===0?<div className="security-empty"><Icon name="map" size={30}/><strong>Aucun point QR</strong><span>Le responsable doit créer les points de ronde du site.</span></div>:<div className="security-card-list">{points.map(p=><article className="security-record-card" key={p.id}><span className="security-record-icon"><b>{p.sequence_number}</b></span><div className="security-record-main"><strong>{p.label}</strong><span>{p.security_sites?.name}</span><small>{p.instructions||'Aucune instruction'}</small></div>{canManage&&<button className="secondary-button compact-button" onClick={()=>void preview(p)}>Voir le QR</button>}</article>)}</div>}</div></section>
 {canManage&&<section className="panel security-list-panel"><div className="panel-header"><div><p className="eyebrow">HISTORIQUE</p><h2>Dernières rondes</h2></div></div><div className="security-card-list">{patrols.filter(p=>p.status!=='in_progress').slice(0,12).map(p=><article className="security-record-card" key={p.id}><span className="security-record-icon"><Icon name="shield" size={20}/></span><div className="security-record-main"><strong>{p.security_sites?.name||'Site'}</strong><span>{p.security_agents?securityPersonName(p.security_agents.first_name,p.security_agents.last_name):'Agent'}</span><small>{formatSecurityDate(p.started_at,{dateStyle:'short',timeStyle:'short'})} · {(p.security_patrol_scans||[]).length} scan(s)</small></div><span className={`security-status-pill ${p.status==='completed'?'completed':'canceled'}`}>{p.status==='completed'?'Terminée':'Abandonnée'}</span></article>)}</div></section>}
 </div>;
}
