import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Icon } from '../components/Icon';
import { useAuth } from '../contexts/AuthContext';
import { useOrganization } from '../contexts/OrganizationContext';
import { generateSecurityLogbookPdf } from '../features/security/logbookPdf';
import { formatSecurityDate, securityPersonName, type SecurityAgentRecord, type SecurityLogbookEntryRecord, type SecuritySiteRecord } from '../features/security/types';
import { closeFileWindow, prepareFileWindow, showBlobDownload } from '../lib/browserFiles';
import { supabase } from '../lib/supabase';

const categories = [
  ['prise_poste','Prise de poste'],['fin_poste','Fin de poste'],['ronde','Ronde effectuée'],['anomalie','Anomalie constatée'],['incident','Incident'],['visiteur','Visiteur / accès'],['livraison','Livraison'],['appel','Appel reçu'],['consigne','Consigne transmise'],['autre','Autre événement']
] as const;
type FormState={siteId:string;agentId:string;category:string;severity:SecurityLogbookEntryRecord['severity'];title:string;details:string;occurredAt:string};
function nowInput(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16);}

export function SecurityLogbookPage(){
 const {organization}=useOrganization();const {user,demoMode}=useAuth();const canManage=['owner','admin','manager'].includes(organization?.role??'viewer');
 const [rows,setRows]=useState<SecurityLogbookEntryRecord[]>([]);const [sites,setSites]=useState<SecuritySiteRecord[]>([]);const [agents,setAgents]=useState<SecurityAgentRecord[]>([]);
 const [form,setForm]=useState<FormState>({siteId:'',agentId:'',category:'ronde',severity:'info',title:'Ronde effectuée',details:'',occurredAt:nowInput()});const [open,setOpen]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');
 const [from,setFrom]=useState(()=>new Date(new Date().setDate(1)).toISOString().slice(0,10));const [to,setTo]=useState(()=>new Date().toISOString().slice(0,10));
 async function load(){if(!organization)return;setLoading(true);setError('');if(demoMode||!supabase){setRows(JSON.parse(localStorage.getItem(`ncr-suite-security-logbook-${organization.id}`)||'[]'));setSites(JSON.parse(localStorage.getItem(`ncr-suite-security-sites-${organization.id}`)||'[]'));setAgents(JSON.parse(localStorage.getItem(`ncr-suite-security-agents-${organization.id}`)||'[]'));setLoading(false);return;}
  const [r,s,a]=await Promise.all([
   supabase.from('security_logbook_entries').select('id,organization_id,site_id,agent_id,occurred_at,category,severity,title,details,status,created_at,security_sites(name,color_hex),security_agents(first_name,last_name)').eq('organization_id',organization.id).gte('occurred_at',`${from}T00:00:00`).lte('occurred_at',`${to}T23:59:59`).order('occurred_at',{ascending:false}),
   supabase.from('security_sites').select('id,organization_id,client_id,name,code,address,postal_code,city,contact_name,contact_phone,hourly_rate_cents,color_hex,timezone,notes,status,created_at,security_clients(company_name)').eq('organization_id',organization.id).eq('status','active').order('name'),
   supabase.from('security_agents').select('id,organization_id,first_name,last_name,employee_number,email,phone,contract_type,weekly_hours,notes,status,linked_user_id,created_at').eq('organization_id',organization.id).eq('status','active').order('last_name')]);
  const e=r.error||s.error||a.error;if(e)setError(`Chargement impossible : ${e.message}`);else{setRows((r.data??[]) as unknown as SecurityLogbookEntryRecord[]);setSites((s.data??[]) as unknown as SecuritySiteRecord[]);setAgents((a.data??[]) as SecurityAgentRecord[]);}setLoading(false);
 }
 useEffect(()=>{void load();},[organization?.id,demoMode,from,to]);
 useEffect(()=>{setForm(v=>({...v,siteId:v.siteId||sites[0]?.id||'',agentId:v.agentId||agents[0]?.id||''}));},[sites,agents]);
 function chooseCategory(value:string){const label=categories.find(([key])=>key===value)?.[1]||'Événement';setForm({...form,category:value,title:label});}
 async function submit(e:FormEvent){e.preventDefault();if(!organization||!user||!form.siteId||!form.agentId)return;setSaving(true);setError('');const payload={organization_id:organization.id,site_id:form.siteId,agent_id:form.agentId,occurred_at:new Date(form.occurredAt).toISOString(),category:form.category,severity:form.severity,title:form.title.trim(),details:form.details.trim()||null,created_by:user.id};
  try{if(demoMode||!supabase){const site=sites.find(s=>s.id===form.siteId),agent=agents.find(a=>a.id===form.agentId);const created={id:crypto.randomUUID(),...payload,status:'open',created_at:new Date().toISOString(),security_sites:site?{name:site.name,color_hex:site.color_hex}:null,security_agents:agent?{first_name:agent.first_name,last_name:agent.last_name}:null};const next=[created,...rows];localStorage.setItem(`ncr-suite-security-logbook-${organization.id}`,JSON.stringify(next));setRows(next as SecurityLogbookEntryRecord[]);}else{const{error:e}=await supabase.from('security_logbook_entries').insert(payload);if(e)throw e;await load();}setForm(v=>({...v,category:'ronde',severity:'info',title:'Ronde effectuée',details:'',occurredAt:nowInput()}));setOpen(false);setSuccess('L’événement a été ajouté à la main courante.');}catch(c){setError(`Enregistrement impossible : ${c instanceof Error?c.message:'erreur inconnue'}`);}finally{setSaving(false);}
 }
 async function process(id:string){if(!organization||!canManage)return;if(demoMode||!supabase)setRows(v=>v.map(r=>r.id===id?{...r,status:'processed'}:r));else{const{error:e}=await supabase.from('security_logbook_entries').update({status:'processed'}).eq('organization_id',organization.id).eq('id',id);if(e){setError(e.message);return;}await load();}setSuccess('Événement marqué comme traité.');}
 async function exportPdf(){if(!organization)return;const target=prepareFileWindow('Préparation de la main courante','Le PDF est en cours de génération.');try{const result=await generateSecurityLogbookPdf(organization,rows,new Date(`${from}T00:00:00`),new Date(`${to}T23:59:59`));const url=URL.createObjectURL(result.blob);showBlobDownload(target,url,result.filename,'Main courante prête');setTimeout(()=>URL.revokeObjectURL(url),120000);}catch(c){closeFileWindow(target);setError(`Export impossible : ${c instanceof Error?c.message:'erreur inconnue'}`);}}
 const totals=useMemo(()=>({all:rows.length,urgent:rows.filter(r=>r.severity==='urgent').length,open:rows.filter(r=>r.status==='open').length}),[rows]);
 if(!organization)return null;return <div className="page security-page"><header className="page-header"><div><p className="eyebrow">SÉCURITÉ PRIVÉE</p><h1>Main courante intelligente</h1><p>Les choix prédéfinis accélèrent la saisie et garantissent un historique homogène.</p></div><div className="security-header-actions">{canManage&&<button className="secondary-button" onClick={()=>void exportPdf()}><Icon name="file" size={18}/>Exporter PDF</button>}<button className="primary-button" onClick={()=>setOpen(true)}><Icon name="plus" size={18}/>Ajouter un événement</button></div></header>
 {open&&<section className="panel security-form-panel"><div className="panel-header"><div><p className="eyebrow">NOUVEL ÉVÉNEMENT</p><h2>Alimenter la main courante</h2></div><button className="secondary-button compact-button" onClick={()=>setOpen(false)}>Fermer</button></div><form className="security-form-grid" onSubmit={submit}><label>Site *<select required value={form.siteId} onChange={e=>setForm({...form,siteId:e.target.value})}>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Agent *<select required value={form.agentId} onChange={e=>setForm({...form,agentId:e.target.value})}>{agents.map(a=><option key={a.id} value={a.id}>{securityPersonName(a.first_name,a.last_name)}</option>)}</select></label><label>Type d’événement<select value={form.category} onChange={e=>chooseCategory(e.target.value)}>{categories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Gravité<select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value as SecurityLogbookEntryRecord['severity']})}><option value="info">Information</option><option value="attention">Attention</option><option value="urgent">Urgent</option></select></label><label>Date et heure<input type="datetime-local" required value={form.occurredAt} onChange={e=>setForm({...form,occurredAt:e.target.value})}/></label><label>Titre *<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="full-field">Détails<textarea rows={4} value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/></label><div className="form-actions full-field"><button className="primary-button" disabled={saving}>{saving?'Enregistrement…':'Enregistrer'}</button></div></form></section>}
 {error&&<div className="error-message page-message">{error}</div>}{success&&<div className="success-message page-message">{success}</div>}
 <section className="security-planning-summary"><article><Icon name="clipboard" size={20}/><div><strong>{totals.all}</strong><span>événements</span></div></article><article><Icon name="alert" size={20}/><div><strong>{totals.urgent}</strong><span>urgents</span></div></article><article><Icon name="activity" size={20}/><div><strong>{totals.open}</strong><span>à traiter</span></div></article></section>
 <section className="panel security-list-panel"><div className="security-toolbar"><div><p className="eyebrow">PÉRIODE</p><h2>Journal des événements</h2></div><div className="security-date-filter"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><span>au</span><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div></div>{loading?<div className="security-empty">Chargement…</div>:rows.length===0?<div className="security-empty"><Icon name="clipboard" size={30}/><strong>Aucun événement</strong><span>La main courante est vide sur cette période.</span></div>:<div className="security-logbook-list">{rows.map(row=><article className={`security-logbook-card ${row.severity}`} key={row.id}><div className="security-logbook-time"><strong>{new Intl.DateTimeFormat('fr-FR',{hour:'2-digit',minute:'2-digit'}).format(new Date(row.occurred_at))}</strong><span>{formatSecurityDate(row.occurred_at)}</span></div><div className="security-record-main"><strong>{row.title}</strong><span>{row.security_sites?.name||'Site'} · {row.security_agents?securityPersonName(row.security_agents.first_name,row.security_agents.last_name):'Agent'}</span><small>{row.details||categories.find(([v])=>v===row.category)?.[1]||row.category}</small></div><span className={`security-status-pill ${row.status==='processed'?'completed':''}`}>{row.status==='processed'?'Traité':'Ouvert'}</span>{canManage&&row.status==='open'&&<button className="secondary-button compact-button" onClick={()=>void process(row.id)}>Marquer traité</button>}</article>)}</div>}</section>
 </div>;
}
