import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Icon } from '../components/Icon';
import { useAuth } from '../contexts/AuthContext';
import { useOrganization } from '../contexts/OrganizationContext';
import { formatSecurityDate, nullableSecurityText, securityPersonName, type SecurityAgentRecord, type SecurityAlertRecord, type SecurityInstructionRecord, type SecuritySiteRecord } from '../features/security/types';
import { supabase } from '../lib/supabase';

type InstructionForm = { siteId: string; title: string; content: string; priority: SecurityInstructionRecord['priority'] };
type AlertForm = { siteId: string; agentId: string; title: string; message: string; severity: SecurityAlertRecord['severity'] };
const emptyInstruction: InstructionForm = { siteId: '', title: '', content: '', priority: 'normal' };
const emptyAlert: AlertForm = { siteId: '', agentId: '', title: '', message: '', severity: 'info' };

export function SecurityInstructionsPage() {
  const { organization } = useOrganization(); const { user, demoMode } = useAuth();
  const canManage = ['owner','admin','manager'].includes(organization?.role ?? 'viewer');
  const [sites, setSites] = useState<SecuritySiteRecord[]>([]); const [agents, setAgents] = useState<SecurityAgentRecord[]>([]);
  const [instructions, setInstructions] = useState<SecurityInstructionRecord[]>([]); const [alerts, setAlerts] = useState<(SecurityAlertRecord & { acknowledged?: boolean })[]>([]);
  const [instruction, setInstruction] = useState<InstructionForm>(emptyInstruction); const [alert, setAlert] = useState<AlertForm>(emptyAlert);
  const [mode, setMode] = useState<'instruction'|'alert'|null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');

  async function load() {
    if (!organization) return; setLoading(true); setError('');
    if (demoMode || !supabase) { setSites(JSON.parse(localStorage.getItem(`ncr-suite-security-sites-${organization.id}`) || '[]')); setAgents(JSON.parse(localStorage.getItem(`ncr-suite-security-agents-${organization.id}`) || '[]')); setInstructions(JSON.parse(localStorage.getItem(`ncr-suite-security-instructions-${organization.id}`) || '[]')); setAlerts(JSON.parse(localStorage.getItem(`ncr-suite-security-alerts-${organization.id}`) || '[]')); setLoading(false); return; }
    const [siteResult, agentResult, instructionResult, alertResult, ackResult] = await Promise.all([
      supabase.from('security_sites').select('id,organization_id,client_id,name,code,address,postal_code,city,contact_name,contact_phone,hourly_rate_cents,color_hex,timezone,notes,status,created_at,security_clients(company_name)').eq('organization_id', organization.id).eq('status','active').order('name'),
      supabase.from('security_agents').select('id,organization_id,first_name,last_name,employee_number,email,phone,contract_type,weekly_hours,notes,status,linked_user_id,created_at').eq('organization_id', organization.id).eq('status','active').order('last_name'),
      supabase.from('security_site_instructions').select('id,organization_id,site_id,title,content,priority,active_from,active_until,status,created_at,security_sites(name,color_hex)').eq('organization_id', organization.id).eq('status','active').order('priority').order('created_at',{ascending:false}),
      supabase.from('security_alerts').select('id,organization_id,site_id,agent_id,title,message,severity,status,resolved_at,created_at,security_sites!security_alerts_site_fk(name,color_hex),security_agents!security_alerts_agent_fk(first_name,last_name)').eq('organization_id', organization.id).eq('status','open').order('created_at',{ascending:false}),
      supabase.from('security_alert_acknowledgements').select('alert_id').eq('organization_id', organization.id)
    ]);
    const firstError = siteResult.error || agentResult.error || instructionResult.error || alertResult.error || ackResult.error;
    if (firstError) setError(`Chargement impossible : ${firstError.message}`); else {
      const ack = new Set((ackResult.data ?? []).map((row) => row.alert_id));
      setSites((siteResult.data ?? []) as unknown as SecuritySiteRecord[]); setAgents((agentResult.data ?? []) as SecurityAgentRecord[]); setInstructions((instructionResult.data ?? []) as unknown as SecurityInstructionRecord[]); setAlerts(((alertResult.data ?? []) as unknown as SecurityAlertRecord[]).map((row) => ({...row, acknowledged: ack.has(row.id)})));
    } setLoading(false);
  }
  useEffect(() => { void load(); }, [organization?.id, demoMode]);
  useEffect(() => { const siteId=sites[0]?.id||''; setInstruction((v)=>({...v,siteId:v.siteId||siteId})); setAlert((v)=>({...v,siteId:v.siteId||siteId})); },[sites]);

  async function saveInstruction(event: FormEvent) {
    event.preventDefault(); if (!organization || !user || !canManage) return; setSaving(true); setError('');
    const payload={organization_id:organization.id,site_id:instruction.siteId,title:instruction.title.trim(),content:instruction.content.trim(),priority:instruction.priority,created_by:user.id};
    try { if (demoMode || !supabase) { const created={id:crypto.randomUUID(),...payload,status:'active',active_from:null,active_until:null,created_at:new Date().toISOString(),security_sites:{name:sites.find(s=>s.id===instruction.siteId)?.name||'Site'}}; const next=[created,...instructions]; localStorage.setItem(`ncr-suite-security-instructions-${organization.id}`,JSON.stringify(next)); setInstructions(next as SecurityInstructionRecord[]); } else { const {error:e}=await supabase.from('security_site_instructions').insert(payload); if(e) throw e; await load(); } setInstruction({...emptyInstruction,siteId:sites[0]?.id||''}); setMode(null); setSuccess('La consigne a été publiée.'); } catch(c){setError(`Publication impossible : ${c instanceof Error?c.message:'erreur inconnue'}`);} finally{setSaving(false);}
  }
  async function saveAlert(event: FormEvent) {
    event.preventDefault(); if (!organization || !user || !canManage) return; setSaving(true); setError('');
    const payload={organization_id:organization.id,site_id:alert.siteId,agent_id:alert.agentId||null,title:alert.title.trim(),message:alert.message.trim(),severity:alert.severity,created_by:user.id};
    try { if (demoMode || !supabase) { const created={id:crypto.randomUUID(),...payload,status:'open',resolved_at:null,created_at:new Date().toISOString(),security_sites:{name:sites.find(s=>s.id===alert.siteId)?.name||'Site'}}; const next=[created,...alerts]; localStorage.setItem(`ncr-suite-security-alerts-${organization.id}`,JSON.stringify(next)); setAlerts(next as (SecurityAlertRecord & {acknowledged?:boolean})[]); } else { const {error:e}=await supabase.from('security_alerts').insert(payload); if(e) throw e; await load(); } setAlert({...emptyAlert,siteId:sites[0]?.id||''}); setMode(null); setSuccess('L’alerte terrain a été envoyée.'); } catch(c){setError(`Envoi impossible : ${c instanceof Error?c.message:'erreur inconnue'}`);} finally{setSaving(false);}
  }
  async function acknowledge(id:string){ if(!organization||!supabase)return; const {error:e}=await supabase.rpc('acknowledge_security_alert',{p_organization_id:organization.id,p_alert_id:id}); if(e)setError(e.message);else {setAlerts(v=>v.map(a=>a.id===id?{...a,acknowledged:true}:a));setSuccess('Alerte prise en compte.');}}
  async function resolve(id:string){ if(!organization||!canManage)return; if(demoMode||!supabase)setAlerts(v=>v.filter(a=>a.id!==id));else {const {error:e}=await supabase.from('security_alerts').update({status:'resolved',resolved_at:new Date().toISOString()}).eq('organization_id',organization.id).eq('id',id);if(e){setError(e.message);return;}await load();}setSuccess('Alerte résolue.');}
  const grouped=useMemo(()=>sites.map(site=>({site,instructions:instructions.filter(i=>i.site_id===site.id),alerts:alerts.filter(a=>a.site_id===site.id)})).filter(g=>g.instructions.length||g.alerts.length),[sites,instructions,alerts]);
  if(!organization)return null;
  return <div className="page security-page"><header className="page-header"><div><p className="eyebrow">SÉCURITÉ PRIVÉE</p><h1>Consignes & alertes</h1><p>Diffuse les informations propres à chaque site et assure leur prise en compte par les agents.</p></div>{canManage&&<div className="security-header-actions"><button className="secondary-button" onClick={()=>setMode('instruction')}><Icon name="clipboard" size={18}/>Nouvelle consigne</button><button className="primary-button" onClick={()=>setMode('alert')}><Icon name="alert" size={18}/>Nouvelle alerte</button></div>}</header>
    {mode==='instruction'&&<section className="panel security-form-panel"><div className="panel-header"><div><p className="eyebrow">CONSIGNE DE SITE</p><h2>Publier une instruction</h2></div><button className="secondary-button compact-button" onClick={()=>setMode(null)}>Fermer</button></div><form className="security-form-grid" onSubmit={saveInstruction}><label>Site *<select required value={instruction.siteId} onChange={e=>setInstruction({...instruction,siteId:e.target.value})}>{sites.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Priorité<select value={instruction.priority} onChange={e=>setInstruction({...instruction,priority:e.target.value as SecurityInstructionRecord['priority']})}><option value="normal">Normale</option><option value="important">Importante</option><option value="critical">Critique</option></select></label><label className="full-field">Titre *<input required value={instruction.title} onChange={e=>setInstruction({...instruction,title:e.target.value})}/></label><label className="full-field">Contenu *<textarea required rows={5} value={instruction.content} onChange={e=>setInstruction({...instruction,content:e.target.value})}/></label><div className="form-actions full-field"><button className="primary-button" disabled={saving}>Publier</button></div></form></section>}
    {mode==='alert'&&<section className="panel security-form-panel"><div className="panel-header"><div><p className="eyebrow">ALERTE TERRAIN</p><h2>Avertir les agents</h2></div><button className="secondary-button compact-button" onClick={()=>setMode(null)}>Fermer</button></div><form className="security-form-grid" onSubmit={saveAlert}><label>Site *<select required value={alert.siteId} onChange={e=>setAlert({...alert,siteId:e.target.value})}>{sites.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Destinataire<select value={alert.agentId} onChange={e=>setAlert({...alert,agentId:e.target.value})}><option value="">Tous les agents du site</option>{agents.map(a=><option value={a.id} key={a.id}>{securityPersonName(a.first_name,a.last_name)}</option>)}</select></label><label>Gravité<select value={alert.severity} onChange={e=>setAlert({...alert,severity:e.target.value as SecurityAlertRecord['severity']})}><option value="info">Information</option><option value="warning">Attention</option><option value="critical">Critique</option></select></label><label>Titre *<input required value={alert.title} onChange={e=>setAlert({...alert,title:e.target.value})}/></label><label className="full-field">Message *<textarea required rows={4} value={alert.message} onChange={e=>setAlert({...alert,message:e.target.value})}/></label><div className="form-actions full-field"><button className="primary-button" disabled={saving}>Envoyer l’alerte</button></div></form></section>}
    {error&&<div className="error-message page-message">{error}</div>}{success&&<div className="success-message page-message">{success}</div>}
    {loading?<div className="security-empty">Chargement…</div>:grouped.length===0?<section className="panel security-empty"><Icon name="clipboard" size={30}/><strong>Aucune consigne ni alerte</strong><span>Les informations publiées par site apparaîtront ici.</span></section>:<div className="security-site-info-groups">{grouped.map(({site,instructions:siteInstructions,alerts:siteAlerts})=><section className="panel security-site-info" key={site.id}><header><span style={{background:site.color_hex||'#0A84FF'}}/><div><p className="eyebrow">SITE</p><h2>{site.name}</h2></div></header>{siteAlerts.map(a=><article className={`security-alert-card ${a.severity}`} key={a.id}><Icon name="alert" size={20}/><div><strong>{a.title}</strong><p>{a.message}</p><small>{formatSecurityDate(a.created_at,{dateStyle:'short',timeStyle:'short'})}{a.security_agents?` · ${securityPersonName(a.security_agents.first_name,a.security_agents.last_name)}`:' · Tous les agents'}</small></div>{canManage?<button className="secondary-button compact-button" onClick={()=>void resolve(a.id)}>Résoudre</button>:<button className="primary-button compact-button" disabled={a.acknowledged} onClick={()=>void acknowledge(a.id)}>{a.acknowledged?'Prise en compte':'J’ai lu'}</button>}</article>)}{siteInstructions.map(i=><article className={`security-instruction-card ${i.priority}`} key={i.id}><Icon name="clipboard" size={20}/><div><strong>{i.title}</strong><p>{i.content}</p><small>Publié le {formatSecurityDate(i.created_at)}</small></div></article>)}</section>)}</div>}
  </div>;
}
