-- NCR Suite V2.8.5 — Commande tactile, cuisine et note provisoire
-- À exécuter après 049_restaurant_public_booking_settings.sql.
-- Aucun encaissement ni moyen de paiement n'est enregistré dans ce module.

begin;

insert into public.module_catalog (
  module_key, display_name, description, category, icon_key,
  compatible_business_types, core_module, default_enabled, active, sort_order
) values
  ('restaurant_ordering', 'Commandes', 'Prise de commande tactile et note provisoire par table.', 'restauration', 'clipboard', '{restauration}', false, true, true, 714),
  ('restaurant_kitchen', 'Cuisine', 'Écran de préparation et suivi des plats envoyés.', 'restauration', 'utensils', '{restauration}', false, false, true, 716)
on conflict (module_key) do update set
  display_name = excluded.display_name,
  description = excluded.description,
  category = excluded.category,
  icon_key = excluded.icon_key,
  compatible_business_types = excluded.compatible_business_types,
  default_enabled = excluded.default_enabled,
  active = excluded.active,
  sort_order = excluded.sort_order,
  updated_at = now();

update public.domain_plan_catalog
set features = coalesce(features, '{}'::jsonb) || jsonb_build_object('restaurant_ordering', true),
    updated_at = now()
where business_type = 'restauration'
  and plan_key in ('decouverte','essentielle','professionnelle','metier');

update public.domain_plan_catalog
set features = coalesce(features, '{}'::jsonb) || jsonb_build_object('restaurant_kitchen_display', true),
    updated_at = now()
where business_type = 'restauration'
  and plan_key in ('essentielle','professionnelle','metier');

update public.domain_plan_catalog
set features = coalesce(features, '{}'::jsonb) || jsonb_build_object('restaurant_advanced_ordering', true),
    updated_at = now()
where business_type = 'restauration'
  and plan_key in ('professionnelle','metier');

insert into public.organization_modules (organization_id,module_key,enabled)
select o.id,m.module_key,true
from public.organizations o
cross join lateral (
  values ('restaurant_ordering','decouverte'), ('restaurant_kitchen','essentielle')
) as m(module_key,minimum_plan)
where o.business_type='restauration'
  and (o.plan<>'metier' or not coalesce(o.metier_modules_configured,false))
  and (m.minimum_plan='decouverte' or o.plan in ('essentielle','professionnelle','metier'))
on conflict (organization_id,module_key) do update set enabled=true;

create table if not exists public.restaurant_orders (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  table_id uuid references public.restaurant_tables(id) on delete set null,
  reservation_id uuid references public.restaurant_reservations(id) on delete set null,
  order_number bigint generated by default as identity,
  status text not null default 'draft' check (status in ('draft','sent','in_progress','ready','served','bill_requested','closed','canceled')),
  guest_count integer not null default 1 check (guest_count between 1 and 100),
  notes text,
  subtotal_cents integer not null default 0 check (subtotal_cents >= 0),
  total_cents integer not null default 0 check (total_cents >= 0),
  opened_by uuid references auth.users(id) on delete set null,
  closed_by uuid references auth.users(id) on delete set null,
  opened_at timestamptz not null default now(),
  bill_requested_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, id)
);

create unique index if not exists idx_restaurant_orders_one_active_per_table
on public.restaurant_orders(organization_id, table_id)
where table_id is not null and status in ('draft','sent','in_progress','ready','served','bill_requested');

create index if not exists idx_restaurant_orders_org_status
on public.restaurant_orders(organization_id, status, opened_at desc);

create table if not exists public.restaurant_order_items (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  order_id uuid not null,
  menu_item_id uuid,
  item_name text not null check (char_length(trim(item_name)) between 1 and 180),
  unit_price_cents integer not null default 0 check (unit_price_cents between 0 and 10000000),
  quantity integer not null default 1 check (quantity between 1 and 99),
  course text not null default 'main' check (course in ('drink','starter','main','dessert','other')),
  station text not null default 'kitchen' check (station in ('kitchen','bar','cold','hot','dessert')),
  notes text,
  status text not null default 'draft' check (status in ('draft','sent','in_progress','ready','served','canceled')),
  sent_at timestamptz,
  started_at timestamptz,
  ready_at timestamptz,
  served_at timestamptz,
  canceled_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, id),
  constraint restaurant_order_items_order_fk foreign key (organization_id, order_id)
    references public.restaurant_orders(organization_id, id) on delete cascade,
  constraint restaurant_order_items_menu_fk foreign key (organization_id, menu_item_id)
    references public.restaurant_menu_items(organization_id, id) on delete set null (menu_item_id)
);

create index if not exists idx_restaurant_order_items_order
on public.restaurant_order_items(organization_id, order_id, status, created_at);

create or replace function public.restaurant_order_access_guard()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.organization_has_plan_feature(new.organization_id, 'restaurant_ordering') then
    raise exception 'La prise de commande n’est pas incluse dans cette offre.';
  end if;
  if not public.is_org_member(new.organization_id) then
    raise exception 'Accès refusé.';
  end if;
  if tg_table_name = 'restaurant_order_items'
     and new.status in ('in_progress','ready','served')
     and not public.organization_has_plan_feature(new.organization_id, 'restaurant_kitchen_display') then
    raise exception 'L’écran Cuisine est disponible à partir de l’offre Essentielle.';
  end if;
  return new;
end;
$$;

create or replace function public.recalculate_restaurant_order(p_order_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org uuid;
  v_total integer;
begin
  select organization_id into v_org from public.restaurant_orders where id = p_order_id;
  if v_org is null then return; end if;

  select coalesce(sum(unit_price_cents * quantity) filter (where status <> 'canceled'), 0)::integer
  into v_total
  from public.restaurant_order_items
  where order_id = p_order_id and organization_id = v_org;

  update public.restaurant_orders
  set subtotal_cents = v_total,
      total_cents = v_total,
      updated_at = now()
  where id = p_order_id;
end;
$$;

create or replace function public.recalculate_restaurant_order_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    perform public.recalculate_restaurant_order(old.order_id);
    return old;
  end if;
  perform public.recalculate_restaurant_order(new.order_id);
  return new;
end;
$$;

create or replace function public.sync_restaurant_table_from_order()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.table_id is null then return new; end if;

  update public.restaurant_tables
  set service_status = case
    when new.status = 'bill_requested' then 'payment'
    when new.status in ('draft','sent','in_progress','ready','served') then 'ordering'
    when new.status = 'closed' then 'cleaning'
    when new.status = 'canceled' then 'available'
    else service_status
  end,
  updated_at = now()
  where id = new.table_id and organization_id = new.organization_id;

  return new;
end;
$$;

create or replace function public.open_restaurant_order(
  p_organization_id uuid,
  p_table_id uuid default null,
  p_guest_count integer default 1,
  p_reservation_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_existing uuid;
begin
  if auth.uid() is null or not public.is_org_member(p_organization_id) then
    raise exception 'Accès refusé.';
  end if;
  if not public.organization_has_plan_feature(p_organization_id, 'restaurant_ordering') then
    raise exception 'La prise de commande n’est pas incluse dans cette offre.';
  end if;

  if p_table_id is not null then
    select id into v_existing
    from public.restaurant_orders
    where organization_id = p_organization_id
      and table_id = p_table_id
      and status in ('draft','sent','in_progress','ready','served','bill_requested')
    order by opened_at desc
    limit 1;
    if v_existing is not null then return v_existing; end if;
  end if;

  insert into public.restaurant_orders(
    organization_id, table_id, reservation_id, guest_count, opened_by
  ) values (
    p_organization_id, p_table_id, p_reservation_id, greatest(1, least(coalesce(p_guest_count,1),100)), auth.uid()
  ) returning id into v_id;

  if p_reservation_id is not null then
    update public.restaurant_reservations
    set status = 'seated', updated_at = now()
    where id = p_reservation_id and organization_id = p_organization_id
      and status in ('pending','confirmed');
  end if;

  return v_id;
end;
$$;

create or replace function public.send_restaurant_order(p_order_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org uuid;
begin
  select organization_id into v_org from public.restaurant_orders where id=p_order_id;
  if v_org is null or not public.is_org_member(v_org) then raise exception 'Commande introuvable.'; end if;
  if not exists(select 1 from public.restaurant_order_items where order_id=p_order_id and status='draft') then
    raise exception 'Aucun nouvel article à envoyer.';
  end if;

  update public.restaurant_order_items
  set status='sent', sent_at=now(), updated_at=now()
  where order_id=p_order_id and status='draft';

  update public.restaurant_orders
  set status='sent', updated_at=now()
  where id=p_order_id and status not in ('closed','canceled');
end;
$$;

create or replace function public.set_restaurant_order_item_status(p_item_id uuid, p_status text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org uuid;
  v_order uuid;
begin
  if p_status not in ('sent','in_progress','ready','served','canceled') then
    raise exception 'Statut invalide.';
  end if;
  select organization_id, order_id into v_org, v_order from public.restaurant_order_items where id=p_item_id;
  if v_org is null or not public.is_org_member(v_org) then raise exception 'Article introuvable.'; end if;

  update public.restaurant_order_items
  set status=p_status,
      started_at=case when p_status='in_progress' then coalesce(started_at,now()) else started_at end,
      ready_at=case when p_status='ready' then coalesce(ready_at,now()) else ready_at end,
      served_at=case when p_status='served' then coalesce(served_at,now()) else served_at end,
      canceled_at=case when p_status='canceled' then coalesce(canceled_at,now()) else canceled_at end,
      updated_at=now()
  where id=p_item_id;

  update public.restaurant_orders o
  set status = case
    when exists(select 1 from public.restaurant_order_items i where i.order_id=o.id and i.status='in_progress') then 'in_progress'
    when exists(select 1 from public.restaurant_order_items i where i.order_id=o.id and i.status='sent') then 'sent'
    when exists(select 1 from public.restaurant_order_items i where i.order_id=o.id and i.status='ready') then 'ready'
    when exists(select 1 from public.restaurant_order_items i where i.order_id=o.id and i.status='served') then 'served'
    else o.status end,
    updated_at=now()
  where o.id=v_order and o.status not in ('bill_requested','closed','canceled');
end;
$$;

create or replace function public.request_restaurant_bill(p_order_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_org uuid;
begin
  select organization_id into v_org from public.restaurant_orders where id=p_order_id;
  if v_org is null or not public.is_org_member(v_org) then raise exception 'Commande introuvable.'; end if;
  update public.restaurant_orders set status='bill_requested', bill_requested_at=now(), updated_at=now() where id=p_order_id;
end;
$$;

create or replace function public.close_restaurant_order_without_payment(p_order_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_org uuid;
begin
  select organization_id into v_org from public.restaurant_orders where id=p_order_id;
  if v_org is null or not public.has_org_role(v_org,array['owner','admin','manager']) then
    raise exception 'Seul un responsable peut clôturer la note.';
  end if;
  update public.restaurant_orders
  set status='closed', closed_by=auth.uid(), closed_at=now(), updated_at=now()
  where id=p_order_id and status not in ('closed','canceled');
end;
$$;

alter table public.restaurant_orders enable row level security;
alter table public.restaurant_order_items enable row level security;

alter table public.restaurant_orders force row level security;
alter table public.restaurant_order_items force row level security;

drop policy if exists restaurant_orders_select on public.restaurant_orders;
create policy restaurant_orders_select on public.restaurant_orders for select
using (public.is_org_member(organization_id));

drop policy if exists restaurant_orders_insert on public.restaurant_orders;
create policy restaurant_orders_insert on public.restaurant_orders for insert
with check (public.is_org_member(organization_id) and public.organization_has_plan_feature(organization_id,'restaurant_ordering'));

drop policy if exists restaurant_orders_update on public.restaurant_orders;
create policy restaurant_orders_update on public.restaurant_orders for update
using (public.is_org_member(organization_id))
with check (public.is_org_member(organization_id));

drop policy if exists restaurant_order_items_select on public.restaurant_order_items;
create policy restaurant_order_items_select on public.restaurant_order_items for select
using (public.is_org_member(organization_id));

drop policy if exists restaurant_order_items_insert on public.restaurant_order_items;
create policy restaurant_order_items_insert on public.restaurant_order_items for insert
with check (public.is_org_member(organization_id) and public.organization_has_plan_feature(organization_id,'restaurant_ordering'));

drop policy if exists restaurant_order_items_update on public.restaurant_order_items;
create policy restaurant_order_items_update on public.restaurant_order_items for update
using (public.is_org_member(organization_id))
with check (public.is_org_member(organization_id));

drop policy if exists restaurant_order_items_delete on public.restaurant_order_items;
create policy restaurant_order_items_delete on public.restaurant_order_items for delete
using (public.is_org_member(organization_id));

drop trigger if exists restaurant_orders_guard_trigger on public.restaurant_orders;
create trigger restaurant_orders_guard_trigger before insert or update on public.restaurant_orders
for each row execute procedure public.restaurant_order_access_guard();

drop trigger if exists restaurant_order_items_guard_trigger on public.restaurant_order_items;
create trigger restaurant_order_items_guard_trigger before insert or update on public.restaurant_order_items
for each row execute procedure public.restaurant_order_access_guard();

drop trigger if exists restaurant_orders_updated_at_trigger on public.restaurant_orders;
create trigger restaurant_orders_updated_at_trigger before update on public.restaurant_orders
for each row execute procedure public.set_updated_at();

drop trigger if exists restaurant_order_items_updated_at_trigger on public.restaurant_order_items;
create trigger restaurant_order_items_updated_at_trigger before update on public.restaurant_order_items
for each row execute procedure public.set_updated_at();

drop trigger if exists restaurant_order_items_recalculate_trigger on public.restaurant_order_items;
create trigger restaurant_order_items_recalculate_trigger
after insert or update or delete on public.restaurant_order_items
for each row execute procedure public.recalculate_restaurant_order_trigger();

drop trigger if exists restaurant_orders_sync_table_trigger on public.restaurant_orders;
create trigger restaurant_orders_sync_table_trigger
after insert or update of status, table_id on public.restaurant_orders
for each row execute procedure public.sync_restaurant_table_from_order();

grant select,insert,update on public.restaurant_orders to authenticated;
grant select,insert,update,delete on public.restaurant_order_items to authenticated;
grant execute on function public.open_restaurant_order(uuid,uuid,integer,uuid) to authenticated;
grant execute on function public.send_restaurant_order(uuid) to authenticated;
grant execute on function public.set_restaurant_order_item_status(uuid,text) to authenticated;
grant execute on function public.request_restaurant_bill(uuid) to authenticated;
grant execute on function public.close_restaurant_order_without_payment(uuid) to authenticated;
grant execute on function public.recalculate_restaurant_order(uuid) to authenticated;

commit;
